export const content = {
    bestRegards: "bestRegards",
    name: "name",
    surname: "surname",
    title: "title",
    place: "place",
    phonePrefix: "phonePrefix",
    phone: "phone",
    emailPrefix: "emailPrefix",
    email: "email",
    websitePrefix: "websitePrefix",
    website: "website",
    websiteLink: "websiteLink",
    addressPrefix: "addressPrefix",
    address: "address",
    address2: "address2",
    disclaimer: "disclaimer",
    availablePrefix: "availablePrefix",
    availableValue: "availableValue",
    slogan: "slogan",
    company: "company",
    youtubeText: "youtubeText",
    youtubeLink: "youtubeLink",
    visitText: "visitText",
};
