// generateRandomId()

import { generateRandomId } from "../utils/generateRandomId";

const getLocalizedContent = () => {
  return {
    name: "Madison Brooks",
    title: "Professional Photographer",
    phonePrefix: "phone: ",
    phoneValue: "+1 201-184-1199",
    emailPrefix: "email: ",
    emailValue: "example@email.com",
    websitePrefix: "web: ",
    websiteValue: "www.example.com",
  };
};

export const signature_b = () => {
  return {
    info: {
      templateSlug: "signature-b",
      "version": "0.1",
      "name": "Signature B",
    },

    "colors": [
      "rgb(0, 0, 0)",
      "rgb(58, 135, 176)",
    ],
    "rows": [
      {
        "id": generateRandomId(),
        "columns": [
          {
            "id": generateRandomId(),
            "rows": [
              {
                "id": generateRandomId(),
                "content": {
                  "type": "image",
                  "components": [
                    {
                      "id": "hyqqp19",
                      "src":
                        `https://${process.env.NEXT_PUBLIC_AWS_S3_BUCKET_NAME}.s3.${process.env.NEXT_PUBLIC_AWS_REGION}.amazonaws.com/examples/signature_b_preview.png`,
                      "padding": "0px 0px 0px 0px",
                      "originalSrc":
                        "https://siphpr.s3.us-east-1.amazonaws.com/examples/signature_b_original.jpg",
                      "borderRadius": "0px",
                      "previewWidth": 135,
                      "imageSettings": {
                        "crop": {
                          "x": 27.48190958900645,
                          "y": 14.928876858897025,
                          "unit": "%",
                          "width": 42.96256759460269,
                          "height": 64.44385479033214,
                        },
                        "aspect": 1,
                        "isCircular": true,
                        "borderRadius": 0,
                      },
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                    },
                  ],
                },
              },
            ],
          },
          {
            "id": generateRandomId(),
            "rows": [
              {
                "id": generateRandomId(),
                "content": {
                  "type": "text",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": getLocalizedContent().name,
                      "color": "rgb(0, 0, 0)",
                      "padding": "0px 0px 0px 0px",
                      "fontSize": "17px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "borderRadius": "0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                    },
                  ],
                },
              },
              {
                "id": "915sz6i",
                "content": {
                  "type": "text",
                  "components": [
                    {
                      "id": "w9q7b5z",
                      "text": getLocalizedContent().title,
                      "color": "rgb(0, 0, 0)",
                      "padding": "7px 0px 7px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "borderRadius": "0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(58, 135, 176)",
                      "borderBottomStyle": "solid",
                      "borderBottomWidth": "2px",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "phone",
                  "components": [
                    {
                      "id": "h4tguv2",
                      "text": getLocalizedContent().phonePrefix,
                      "type": "text",
                      "color": "rgb(58, 135, 176)",
                      "padding": "7px 0px 0px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "borderRadius": "0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                    },
                    {
                      "id": generateRandomId(),
                      "text": getLocalizedContent().phoneValue,
                      "type": "phoneLink",
                      "color": "rgb(0, 0, 0)",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "normal",
                      "lineHeight": "1.25",
                      "letterSpacing": "0px",
                      "textDecoration": "none",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "email",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": getLocalizedContent().emailPrefix,
                      "type": "text",
                      "color": "rgb(58, 135, 176)",
                      "padding": "0px 0px 0px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "borderRadius": "0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                    },
                    {
                      "id": generateRandomId(),
                      "text": getLocalizedContent().emailValue,
                      "type": "emailLink",
                      "color": "rgb(0, 0, 0)",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "normal",
                      "lineHeight": "1.25",
                      "letterSpacing": "0px",
                      "textDecoration": "none",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "website",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": getLocalizedContent().websitePrefix,
                      "type": "text",
                      "color": "rgb(58, 135, 176)",
                      "padding": "0px 0px 0px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "borderRadius": "0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                    },
                    {
                      "id": generateRandomId(),
                      "text": getLocalizedContent().websiteValue,
                      "type": "websiteLink",
                      "color": "rgb(0, 0, 0)",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "normal",
                      "lineHeight": "1.25",
                      "letterSpacing": "0px",
                      "textDecoration": "none",
                    },
                  ],
                },
              },
            ],
            "style": {
              "padding": "0px 0px 0px 10px",
              "borderRadius": "0",
              "verticalAlign": "middle",
              "borderTopColor": "rgb(0, 0, 0)",
              "borderTopStyle": "none",
              "borderTopWidth": "0px",
              "borderLeftColor": "rgb(0, 0, 0)",
              "borderLeftStyle": "none",
              "borderLeftWidth": "0px",
              "borderRightColor": "rgb(0, 0, 0)",
              "borderRightStyle": "none",
              "borderRightWidth": "0px",
              "borderBottomColor": "rgb(0, 0, 0)",
              "borderBottomStyle": "none",
              "borderBottomWidth": "0px",
            },
          },
        ],
      },
    ],
  };
};
