// generateRandomId()

import { generateRandomId } from "../utils/generateRandomId";
import { content } from "./constants";

const getLocalizedContent = () => {
  return {
    [content.name]: "Madison Brooks",
    [content.title]: "Professional Photographer",
    [content.phonePrefix]: "p: ",
    [content.phone]: "+1 201-184-1199",
    [content.emailPrefix]: "e: ",
    [content.email]: "example@email.com",
    [content.websitePrefix]: "",
    [content.website]: "www.example.com",
    [content.websiteLink]: "example.com",
  };
};

export const signature_b = () => {
  const localizedContent = getLocalizedContent();
  return {
    info: {
      templateSlug: "signature-b",
      "version": "0.1",
      "name": "Signature B",
    },

    "colors": [
      "rgb(0, 0, 0)",
      "rgb(58, 135, 176)",
    ],
    "dimensions": {
      "spaces": ["7", "10"],
      "corners": [],
      "borders": ["2"],
      "lengths": [],
    },
    "rows": [
      {
        "id": generateRandomId(),
        "columns": [
          {
            "id": generateRandomId(),
            "rows": [
              {
                "id": generateRandomId(),
                "content": {
                  "type": "image",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "src":
                        `https://${process.env.NEXT_PUBLIC_AWS_S3_BUCKET_NAME}.s3.${process.env.NEXT_PUBLIC_AWS_REGION}.amazonaws.com/examples/signature_b_preview.png`,
                      "padding": "0px 0px 0px 0px",
                      "margin": "0 auto 0 0",
                      "originalSrc":
                        `https://${process.env.NEXT_PUBLIC_AWS_S3_BUCKET_NAME}.s3.${process.env.NEXT_PUBLIC_AWS_REGION}.amazonaws.com/examples/signature_b_original.jpg`,
                      "borderRadius": "0px",
                      "previewWidth": 135,
                      "imageSettings": {
                        "crop": {
                          "x": 27.48190958900645,
                          "y": 14.928876858897025,
                          "unit": "%",
                          "width": 42.96256759460269,
                          "height": 64.44385479033214,
                        },
                        "aspect": 1,
                        "isCircular": true,
                        "borderRadius": {
                          "topLeft": 0,
                          "topRight": 0,
                          "bottomRight": 0,
                          "bottomLeft": 0,
                        },
                      },
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                    },
                  ],
                },
              },
            ],
          },
          {
            "id": generateRandomId(),
            "rows": [
              {
                "id": generateRandomId(),
                "content": {
                  "type": "text",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": localizedContent[content.name],
                      "color": "rgb(0, 0, 0)",
                      "padding": "0px 0px 0px 0px",
                      "fontSize": "17px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "borderRadius": "0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                      "whiteSpace": "nowrap",
                    },
                  ],
                },
              },
              {
                "id": "915sz6i",
                "content": {
                  "type": "text",
                  "components": [
                    {
                      "id": "w9q7b5z",
                      "text": localizedContent[content.title],
                      "color": "rgb(0, 0, 0)",
                      "padding": "7px 0px 7px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "borderRadius": "0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(58, 135, 176)",
                      "borderBottomStyle": "solid",
                      "borderBottomWidth": "2px",
                      "whiteSpace": "nowrap",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "phone",
                  "components": [
                    {
                      "id": "h4tguv2",
                      "text": localizedContent[content.phonePrefix],
                      "type": "text",
                      "color": "rgb(58, 135, 176)",
                      "padding": "7px 0px 0px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "borderRadius": "0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                      "whiteSpace": "nowrap",
                    },
                    {
                      "id": generateRandomId(),
                      "text": localizedContent[content.phone],
                      "type": "phoneLink",
                      "color": "rgb(0, 0, 0)",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "normal",
                      "lineHeight": "1.25",
                      "letterSpacing": "0px",
                      "textDecoration": "none",
                      "whiteSpace": "nowrap",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "email",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": localizedContent[content.emailPrefix],
                      "type": "text",
                      "color": "rgb(58, 135, 176)",
                      "padding": "0px 0px 0px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "borderRadius": "0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                      "whiteSpace": "nowrap",
                    },
                    {
                      "id": generateRandomId(),
                      "text": localizedContent[content.email],
                      "type": "emailLink",
                      "color": "rgb(0, 0, 0)",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "normal",
                      "lineHeight": "1.25",
                      "letterSpacing": "0px",
                      "textDecoration": "none",
                      "whiteSpace": "nowrap",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "website",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": localizedContent[content.websitePrefix],
                      "type": "text",
                      "color": "rgb(58, 135, 176)",
                      "padding": "0px 0px 0px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "borderRadius": "0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                      "whiteSpace": "nowrap",
                    },
                    {
                      "id": generateRandomId(),
                      "link": localizedContent[content.websiteLink],
                      "text": localizedContent[content.website],
                      "type": "websiteLink",
                      "color": "rgb(0, 0, 0)",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "normal",
                      "lineHeight": "1.25",
                      "letterSpacing": "0px",
                      "textDecoration": "none",
                      "whiteSpace": "nowrap",
                    },
                  ],
                },
              },
            ],
            "style": {
              "padding": "0px 0px 0px 10px",
              "borderRadius": "0",
              "verticalAlign": "middle",
              "borderTopColor": "rgb(0, 0, 0)",
              "borderTopStyle": "none",
              "borderTopWidth": "0px",
              "borderLeftColor": "rgb(0, 0, 0)",
              "borderLeftStyle": "none",
              "borderLeftWidth": "0px",
              "borderRightColor": "rgb(0, 0, 0)",
              "borderRightStyle": "none",
              "borderRightWidth": "0px",
              "borderBottomColor": "rgb(0, 0, 0)",
              "borderBottomStyle": "none",
              "borderBottomWidth": "0px",
            },
          },
        ],
      },
    ],
  };
};
