import { generateRandomId } from "../utils/generateRandomId";

const getLocalizedContent = () => {
  return {
    "name": "Jason Smith",
    "title": "Sales consultant",
    "phone": "+1 123 456 7890",
    "email": "example@email.com",
    "website": "www.example.com",
  };
};

export const signature_a = () => {
  const localizedContent = getLocalizedContent();

  return {
    info: {
      templateSlug: "signature-a",
      version: "0.1",
      name: "Signature A",
    },
    "colors": [
      "rgb(0, 0, 0)",
      "rgb(255, 255, 255)",
      "rgb(32, 161, 117)",
    ],
    "rows": [
      {
        "id": generateRandomId(),
        "columns": [
          {
            "id": generateRandomId(),
            "rows": [
              {
                "id": generateRandomId(),
                "content": {
                  "type": "image",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "src":
                        "https://signatures-photos-dev.s3.us-east-1.amazonaws.com/192ebc69-7ff7-4336-b1fc/f1f3f2f0/yyf355b.png",
                      "padding": "0px 0px 0px 0px",
                      "originalSrc":
                        "https://signatures-photos-dev.s3.us-east-1.amazonaws.com/192ebc69-7ff7-4336-b1fc/f1f3f2f0/yyf355b-x6qx.png",
                      "borderRadius": "0",
                      "previewWidth": 140,
                      "imageSettings": {
                        "crop": {
                          "x": 35.43146357659559,
                          "y": 11.765148336215585,
                          "unit": "%",
                          "width": 29.672144619847774,
                          "height": 33.38128846512494,
                        },
                        "aspect": 0.6666666666666666,
                        "isCircular": false,
                        "borderRadius": 10,
                      },
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                    },
                  ],
                },
              },
            ],
            "style": {
              "padding": "0px 10px 0px 0px",
              "borderRadius": "0",
              "verticalAlign": "top",
              "borderTopColor": "rgb(0, 0, 0)",
              "borderTopStyle": "none",
              "borderTopWidth": "0px",
              "borderLeftColor": "rgb(0, 0, 0)",
              "borderLeftStyle": "none",
              "borderLeftWidth": "0px",
              "borderRightColor": "rgb(0, 0, 0)",
              "borderRightStyle": "none",
              "borderRightWidth": "0px",
              "borderBottomColor": "rgb(0, 0, 0)",
              "borderBottomStyle": "none",
              "borderBottomWidth": "0px",
            },
          },
          {
            "id": generateRandomId(),
            "rows": [
              {
                "id": generateRandomId(),
                "content": {
                  "type": "text",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": localizedContent.name,
                      "type": "text",
                      "color": "rgb(255, 255, 255)",
                      "padding": "0px 0px 0px 0px",
                      "fontSize": "25px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Tahoma",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "borderRadius": "0",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "text",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": localizedContent.title,
                      "type": "text",
                      "color": "rgb(255, 255, 255)",
                      "padding": "5px 0px 15px 0px",
                      "fontSize": "17px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Arial",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "borderRadius": "0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "phone",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": "P: ",
                      "type": "text",
                      "color": "rgb(255, 255, 255)",
                      "padding": "0px 0px 5px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Arial",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "borderRadius": "0",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                    },
                    {
                      "id": generateRandomId(),
                      "text": localizedContent.phone,
                      "type": "phoneLink",
                      "color": "rgb(255, 255, 255)",
                      "fontSize": "12px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Arial",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "letterSpacing": "0px",
                      "textDecoration": "none",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "email",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": "E: ",
                      "type": "text",
                      "color": "rgb(255, 255, 255)",
                      "padding": "0px 0px 0px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Arial",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "borderRadius": "0",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                    },
                    {
                      "id": generateRandomId(),
                      "text": localizedContent.email,
                      "type": "emailLink",
                      "color": "rgb(255, 255, 255)",
                      "fontSize": "12px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Arial",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "letterSpacing": "0px",
                      "textDecoration": "none",
                    },
                  ],
                },
              },
            ],
            "style": {
              "padding": "20px 20px 0px 20px",
              "borderRadius": "10px",
              "verticalAlign": "top",
              "borderTopColor": "rgb(0, 0, 0)",
              "borderTopStyle": "none",
              "borderTopWidth": "0px",
              "backgroundColor": "rgb(32, 161, 117)",
              "borderLeftColor": "rgb(0, 0, 0)",
              "borderLeftStyle": "none",
              "borderLeftWidth": "0px",
              "borderRightColor": "rgb(0, 0, 0)",
              "borderRightStyle": "none",
              "borderRightWidth": "0px",
              "borderBottomColor": "rgb(0, 0, 0)",
              "borderBottomStyle": "none",
              "borderBottomWidth": "0px",
            },
          },
        ],
      },
    ],
  };
};
