import { generateRandomId } from "../utils/generateRandomId";

const getLocalizedContent = () => {
    return {
        name: "Brian O'Connell",
        title: "Warehouse & Dispatch Supervisor",
        phonePrefix: "📞 ",
        phoneValue: "+1 (555) 456-7890",
        emailPrefix: "✉️ ",
        emailValue: "example@email.com",
        company: "NexusLogistics",
        address: "500 Express Way, Suite B, Rapid City, RC 99001",
        slogan: "Keeping Your Goods Moving, On Time.",
    };
};

export const signature_j = () => {
    const localizedContent = getLocalizedContent();
    return {
        info: {
            templateSlug: "signature-j",
            version: "0.1",
            name: "Signature J",
        },
        colors: [
            "rgb(47, 133, 135)",
            "rgb(55, 121, 166)",
        ],
        rows: [
            {
                id: generateRandomId(),
                columns: [
                    {
                        id: generateRandomId(),
                        rows: [
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "text",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.name,
                                            color: "rgb(47, 133, 135)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 5px 0px",
                                            fontSize: "24px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Helvetica",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "text",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.title,
                                            color: "rgb(55, 121, 166)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 15px 0px",
                                            fontSize: "16px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Helvetica",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "phone",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.phonePrefix,
                                            type: "text",
                                            color: "rgb(0, 0, 0)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 7px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Helvetica",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                        },
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.phoneValue,
                                            type: "phoneLink",
                                            color: "rgb(55, 121, 166)",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            letterSpacing: "0px",
                                            textDecoration: "none",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "email",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.emailPrefix,
                                            type: "text",
                                            color: "rgb(0, 0, 0)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 15px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Helvetica",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                        },
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.emailValue,
                                            type: "emailLink",
                                            color: "rgb(55, 121, 166)",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            letterSpacing: "0px",
                                            textDecoration: "none",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "text",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.company,
                                            color: "rgb(55, 121, 166)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 5px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "text",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.address,
                                            color: "rgb(55, 121, 166)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 10px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Helvetica",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "image",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            src: `https://${process.env.NEXT_PUBLIC_AWS_S3_BUCKET_NAME}.s3.${process.env.NEXT_PUBLIC_AWS_REGION}.amazonaws.com/examples/signature_j_preview.png`,
                                            width: "0px",
                                            height: "0px",
                                            margin: "0 auto 0 0",
                                            padding: "0px 0px 15px 0px",
                                            originalSrc:
                                                `https://${process.env.NEXT_PUBLIC_AWS_S3_BUCKET_NAME}.s3.${process.env.NEXT_PUBLIC_AWS_REGION}.amazonaws.com/examples/signature_j_original.jpg`,
                                            borderRadius: "0px 0px 0px 0px",
                                            previewWidth: 301,
                                            imageSettings: {
                                                crop: {
                                                    x: 0.6018221718924265,
                                                    y: 20.896954651990118,
                                                    unit: "%",
                                                    width: 99.39817782810756,
                                                    height: 68.00757707539864,
                                                },
                                                aspect: "free",
                                                isCircular: false,
                                                borderRadius: {
                                                    topLeft: 5,
                                                    topRight: 5,
                                                    bottomLeft: 5,
                                                    bottomRight: 5,
                                                },
                                            },
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "text",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.slogan,
                                            color: "rgb(55, 121, 166)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 5px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "center",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                        },
                                    ],
                                },
                            },
                        ],
                    },
                ],
            },
        ],
    };
};
