import { generateRandomId } from '../utils/generateRandomId';
import { content } from './constants';

const getLocalizedContent = () => {
  return {
    [content.name]: 'Adeline Waren',
    [content.title]: 'landscape architect',
    [content.phonePrefix]: '',
    [content.phone]: '+1 123 456 7890',
    [content.emailPrefix]: '',
    [content.email]: 'example@email.com',
    [content.websitePrefix]: '',
    [content.website]: 'example.com',
    [content.websiteLink]: 'example.com',
    [content.slogan]: 'Turning your vision into a stunning landscape reality.',
  };
};

export const signature_i = () => {
  const localizedContent = getLocalizedContent();
  return {
    info: {
      templateSlug: 'signature-i',
      version: '0.1',
      name: 'Signature I',
    },
    colors: ['rgb(71, 71, 71)', 'rgb(109, 143, 118)', 'rgb(204, 120, 43)'],
    dimensions: {
      spaces: ['50', '25', '10', '6', '5'],
      corners: ['60'],
      borders: [],
      lengths: [],
    },
    rows: [
      {
        id: generateRandomId(),
        columns: [
          {
            id: generateRandomId(),
            rows: [
              {
                id: generateRandomId(),
                content: {
                  type: 'image',
                  components: [
                    {
                      id: generateRandomId(),
                      src: `https://${process.env.NEXT_PUBLIC_AWS_S3_BUCKET_NAME}.s3.${process.env.NEXT_PUBLIC_AWS_REGION}.amazonaws.com/examples/signature_i_preview.png`,
                      width: '0px',
                      height: '0px',
                      margin: '0 auto 0 0',
                      padding: '0px 0px 0px 0px',
                      originalSrc: `https://${process.env.NEXT_PUBLIC_AWS_S3_BUCKET_NAME}.s3.${process.env.NEXT_PUBLIC_AWS_REGION}.amazonaws.com/examples/signature_i_original.jpg`,
                      borderRadius: '0px 0px 0px 0px',
                      previewWidth: 120,
                      imageSettings: {
                        crop: {
                          x: 17.90408434186663,
                          y: 27.69051940352828,
                          unit: '%',
                          width: 71.62107110401944,
                          height: 50.765597025553376,
                        },
                        aspect: 'free',
                        isCircular: false,
                        borderRadius: {
                          topLeft: 60,
                          topRight: 0,
                          bottomLeft: 0,
                          bottomRight: 60,
                        },
                      },
                      borderTopColor: 'rgb(0, 0, 0)',
                      borderTopStyle: 'none',
                      borderTopWidth: '0px',
                      borderLeftColor: 'rgb(0, 0, 0)',
                      borderLeftStyle: 'none',
                      borderLeftWidth: '0px',
                      borderRightColor: 'rgb(0, 0, 0)',
                      borderRightStyle: 'none',
                      borderRightWidth: '0px',
                      borderBottomColor: 'rgb(0, 0, 0)',
                      borderBottomStyle: 'none',
                      borderBottomWidth: '0px',
                    },
                  ],
                },
              },
            ],
            style: {
              verticalAlign: 'top',
            },
          },
          {
            id: generateRandomId(),
            rows: [
              {
                id: generateRandomId(),
                content: {
                  type: 'text',
                  components: [
                    {
                      id: generateRandomId(),
                      text: localizedContent[content.name],
                      color: 'rgb(204, 120, 43)',
                      width: '0px',
                      height: '0px',
                      padding: '0px 0px 5px 0px',
                      fontSize: '22px',
                      fontStyle: 'normal',
                      textAlign: 'right',
                      fontFamily: 'Arial',
                      fontWeight: 'bold',
                      lineHeight: '1',
                      borderRadius: '0',
                      letterSpacing: '0px',
                      borderTopColor: 'rgb(0, 0, 0)',
                      borderTopStyle: 'none',
                      borderTopWidth: '0px',
                      textDecoration: 'none',
                      borderLeftColor: 'rgb(0, 0, 0)',
                      borderLeftStyle: 'none',
                      borderLeftWidth: '0px',
                      borderRightColor: 'rgb(0, 0, 0)',
                      borderRightStyle: 'none',
                      borderRightWidth: '0px',
                      borderBottomColor: 'rgb(0, 0, 0)',
                      borderBottomStyle: 'none',
                      borderBottomWidth: '0px',
                      whiteSpace: 'nowrap',
                    },
                  ],
                },
              },
              {
                id: generateRandomId(),
                content: {
                  type: 'text',
                  components: [
                    {
                      id: generateRandomId(),
                      text: localizedContent[content.title],
                      color: 'rgb(109, 143, 118)',
                      width: '0px',
                      height: '0px',
                      padding: '0px 0px 5px 0px',
                      fontSize: '18px',
                      fontStyle: 'normal',
                      textAlign: 'right',
                      fontFamily: 'Arial',
                      fontWeight: 'bold',
                      lineHeight: '1',
                      borderRadius: '0px 0px 0px 0px',
                      letterSpacing: '0px',
                      borderTopColor: 'rgb(0, 0, 0)',
                      borderTopStyle: 'none',
                      borderTopWidth: '0px',
                      textDecoration: 'none',
                      borderLeftColor: 'rgb(0, 0, 0)',
                      borderLeftStyle: 'none',
                      borderLeftWidth: '0px',
                      borderRightColor: 'rgb(0, 0, 0)',
                      borderRightStyle: 'none',
                      borderRightWidth: '0px',
                      borderBottomColor: 'rgb(0, 0, 0)',
                      borderBottomStyle: 'none',
                      borderBottomWidth: '0px',
                      whiteSpace: 'nowrap',
                    },
                  ],
                },
              },
              {
                id: generateRandomId(),
                content: {
                  type: 'phone',
                  components: [
                    {
                      id: generateRandomId(),
                      text: localizedContent[content.phonePrefix],
                      type: 'text',
                      color: 'rgb(71, 71, 71)',
                      width: '0px',
                      height: '0px',
                      padding: '10px 0px 5px 0px',
                      fontSize: '14px',
                      fontStyle: 'normal',
                      textAlign: 'right',
                      fontFamily: 'Arial',
                      fontWeight: 'bold',
                      lineHeight: '1',
                      borderRadius: '0px 0px 0px 0px',
                      letterSpacing: '0px',
                      borderTopColor: 'rgb(0, 0, 0)',
                      borderTopStyle: 'none',
                      borderTopWidth: '0px',
                      textDecoration: 'none',
                      borderLeftColor: 'rgb(0, 0, 0)',
                      borderLeftStyle: 'none',
                      borderLeftWidth: '0px',
                      borderRightColor: 'rgb(0, 0, 0)',
                      borderRightStyle: 'none',
                      borderRightWidth: '0px',
                      borderBottomColor: 'rgb(0, 0, 0)',
                      borderBottomStyle: 'none',
                      borderBottomWidth: '0px',
                      whiteSpace: 'nowrap',
                    },
                    {
                      id: generateRandomId(),
                      text: localizedContent[content.phone],
                      type: 'phoneLink',
                      color: 'rgb(71, 71, 71)',
                      fontSize: '14px',
                      fontStyle: 'normal',
                      textAlign: 'right',
                      fontFamily: 'Arial',
                      fontWeight: 'bold',
                      lineHeight: '1',
                      letterSpacing: '0px',
                      textDecoration: 'none',
                      whiteSpace: 'nowrap',
                    },
                  ],
                },
              },
              {
                id: generateRandomId(),
                content: {
                  type: 'email',
                  components: [
                    {
                      id: generateRandomId(),
                      text: localizedContent[content.emailPrefix],
                      type: 'text',
                      color: 'rgb(71, 71, 71)',
                      width: '0px',
                      height: '0px',
                      padding: '0px 0px 5px 0px',
                      fontSize: '14px',
                      fontStyle: 'normal',
                      textAlign: 'right',
                      fontFamily: 'Arial',
                      fontWeight: 'bold',
                      lineHeight: '1',
                      borderRadius: '0px 0px 0px 0px',
                      letterSpacing: '0px',
                      borderTopColor: 'rgb(0, 0, 0)',
                      borderTopStyle: 'none',
                      borderTopWidth: '0px',
                      textDecoration: 'none',
                      borderLeftColor: 'rgb(0, 0, 0)',
                      borderLeftStyle: 'none',
                      borderLeftWidth: '0px',
                      borderRightColor: 'rgb(0, 0, 0)',
                      borderRightStyle: 'none',
                      borderRightWidth: '0px',
                      borderBottomColor: 'rgb(0, 0, 0)',
                      borderBottomStyle: 'none',
                      borderBottomWidth: '0px',
                      whiteSpace: 'nowrap',
                    },
                    {
                      id: generateRandomId(),
                      text: localizedContent[content.email],
                      type: 'emailLink',
                      color: 'rgb(71, 71, 71)',
                      fontSize: '14px',
                      fontStyle: 'normal',
                      textAlign: 'right',
                      fontFamily: 'Arial',
                      fontWeight: 'bold',
                      lineHeight: '1',
                      letterSpacing: '0px',
                      textDecoration: 'none',
                      whiteSpace: 'nowrap',
                    },
                  ],
                },
              },
              {
                id: generateRandomId(),
                content: {
                  type: 'website',
                  components: [
                    {
                      id: generateRandomId(),
                      text: localizedContent[content.websitePrefix],
                      type: 'text',
                      color: 'rgb(71, 71, 71)',
                      width: '0px',
                      height: '0px',
                      padding: '0px 0px 0px 0px',
                      fontSize: '14px',
                      fontStyle: 'normal',
                      textAlign: 'right',
                      fontFamily: 'Arial',
                      fontWeight: 'bold',
                      lineHeight: '1',
                      borderRadius: '0px 0px 0px 0px',
                      letterSpacing: '0px',
                      borderTopColor: 'rgb(0, 0, 0)',
                      borderTopStyle: 'none',
                      borderTopWidth: '0px',
                      textDecoration: 'none',
                      borderLeftColor: 'rgb(0, 0, 0)',
                      borderLeftStyle: 'none',
                      borderLeftWidth: '0px',
                      borderRightColor: 'rgb(0, 0, 0)',
                      borderRightStyle: 'none',
                      borderRightWidth: '0px',
                      borderBottomColor: 'rgb(0, 0, 0)',
                      borderBottomStyle: 'none',
                      borderBottomWidth: '0px',
                      whiteSpace: 'nowrap',
                    },
                    {
                      id: generateRandomId(),
                      link: localizedContent[content.websiteLink],
                      text: localizedContent[content.website],
                      type: 'websiteLink',
                      color: 'rgb(71, 71, 71)',
                      fontSize: '14px',
                      fontStyle: 'normal',
                      textAlign: 'right',
                      fontFamily: 'Arial',
                      fontWeight: 'bold',
                      lineHeight: '1',
                      letterSpacing: '0px',
                      textDecoration: 'none',
                      whiteSpace: 'nowrap',
                    },
                  ],
                },
              },
            ],
            style: {
              width: 'auto',
              height: 'auto',
              padding: '0px 0px 0px 50px',
              borderRadius: '0px 0px 0px 0px',
              verticalAlign: 'middle',
              borderTopColor: 'rgb(0, 0, 0)',
              borderTopStyle: 'none',
              borderTopWidth: '0px',
              borderLeftColor: 'rgb(0, 0, 0)',
              borderLeftStyle: 'none',
              borderLeftWidth: '0px',
              borderRightColor: 'rgb(0, 0, 0)',
              borderRightStyle: 'none',
              borderRightWidth: '0px',
              borderBottomColor: 'rgb(0, 0, 0)',
              borderBottomStyle: 'none',
              borderBottomWidth: '0px',
            },
          },
        ],
      },
      {
        id: generateRandomId(),
        columns: [
          {
            id: generateRandomId(),
            rows: [
              {
                id: generateRandomId(),
                content: {
                  type: 'text',
                  components: [
                    {
                      id: generateRandomId(),
                      text: localizedContent[content.slogan],
                      color: 'rgb(71, 71, 71)',
                      width: '0px',
                      height: '0px',
                      padding: '25px 0px 5px 6px',
                      fontSize: '14px',
                      fontStyle: 'italic',
                      textAlign: 'left',
                      fontFamily: 'Arial',
                      fontWeight: 'normal',
                      lineHeight: '1',
                      borderRadius: '0px 0px 0px 0px',
                      letterSpacing: '0px',
                      borderTopColor: 'rgb(0, 0, 0)',
                      borderTopStyle: 'none',
                      borderTopWidth: '0px',
                      textDecoration: 'none',
                      borderLeftColor: 'rgb(0, 0, 0)',
                      borderLeftStyle: 'none',
                      borderLeftWidth: '0px',
                      borderRightColor: 'rgb(0, 0, 0)',
                      borderRightStyle: 'none',
                      borderRightWidth: '0px',
                      borderBottomColor: 'rgb(0, 0, 0)',
                      borderBottomStyle: 'none',
                      borderBottomWidth: '0px',
                      whiteSpace: 'nowrap',
                    },
                  ],
                },
              },
            ],
          },
        ],
      },
    ],
  };
};
