export const signature_e = () => {
    return {
        "info": {
            templateSlug: "signature-e",
            version: "0.1",
            name: "Signature E",
        },
        "colors": [
            "rgb(0, 0, 0)",
            "rgb(241, 225, 250)",
            "rgb(65, 26, 138)",
        ],
        "rows": [
            {
                "id": "5nmsauu",
                "columns": [
                    {
                        "id": "and6v59",
                        "rows": [
                            {
                                "id": "10kb0e7",
                                "content": {
                                    "type": "image",
                                    "components": [
                                        {
                                            "id": "h89pvaa",
                                            "src":
                                                "https://siph-dev-kfdh6.s3.us-east-1.amazonaws.com/e4c73af2-6711-48e9-9b0e/24552dd1/h89pvaa.png",
                                            "width": "0px",
                                            "height": "0px",
                                            "margin": "0 auto 0 0",
                                            "padding": "0px 0px 0px 0px",
                                            "originalSrc":
                                                "https://siph-dev-kfdh6.s3.us-east-1.amazonaws.com/e4c73af2-6711-48e9-9b0e/24552dd1/h89pvaa-gc2f.jpg",
                                            "borderRadius": "0px 0px 0px 0px",
                                            "previewWidth": 98,
                                            "imageSettings": {
                                                "crop": {
                                                    "x": 27.320800365332133,
                                                    "y": 15.164406051700732,
                                                    "unit": "%",
                                                    "width": 64.79973050489357,
                                                    "height": 66.88893937243822,
                                                },
                                                "aspect": "free",
                                                "isCircular": false,
                                                "borderRadius": {
                                                    "topLeft": 35,
                                                    "topRight": 35,
                                                    "bottomLeft": 35,
                                                    "bottomRight": 35,
                                                },
                                            },
                                            "borderTopColor": "rgb(0, 0, 0)",
                                            "borderTopStyle": "none",
                                            "borderTopWidth": "0px",
                                            "borderLeftColor": "rgb(0, 0, 0)",
                                            "borderLeftStyle": "none",
                                            "borderLeftWidth": "0px",
                                            "borderRightColor": "rgb(0, 0, 0)",
                                            "borderRightStyle": "none",
                                            "borderRightWidth": "0px",
                                            "borderBottomColor": "rgb(0, 0, 0)",
                                            "borderBottomStyle": "none",
                                            "borderBottomWidth": "0px",
                                        },
                                    ],
                                },
                            },
                        ],
                        "style": {
                            "width": "auto",
                            "height": "auto",
                            "padding": "15px 10px 15px 10px",
                            "borderRadius": "0px 0px 0px 0px",
                            "verticalAlign": "top",
                            "borderTopColor": "rgb(0, 0, 0)",
                            "borderTopStyle": "none",
                            "borderTopWidth": "0px",
                            "backgroundColor": "rgb(241, 225, 250)",
                            "borderLeftColor": "rgb(65, 26, 138)",
                            "borderLeftStyle": "solid",
                            "borderLeftWidth": "5px",
                            "borderRightColor": "rgb(0, 0, 0)",
                            "borderRightStyle": "none",
                            "borderRightWidth": "0px",
                            "borderBottomColor": "rgb(0, 0, 0)",
                            "borderBottomStyle": "none",
                            "borderBottomWidth": "0px",
                        },
                    },
                    {
                        "id": "z3t3dfi",
                        "rows": [
                            {
                                "id": "s813o5d",
                                "content": {
                                    "type": "text",
                                    "components": [
                                        {
                                            "id": "poqyqi0",
                                            "text": "Isabella Thompson",
                                            "color": "rgb(65, 26, 138)",
                                            "width": "0px",
                                            "height": "0px",
                                            "padding": "0px 0px 0px 0px",
                                            "fontSize": "18px",
                                            "fontStyle": "normal",
                                            "textAlign": "left",
                                            "fontFamily": "Verdana",
                                            "fontWeight": "bold",
                                            "lineHeight": "1",
                                            "borderRadius": "0",
                                            "letterSpacing": "0px",
                                            "borderTopColor": "rgb(0, 0, 0)",
                                            "borderTopStyle": "none",
                                            "borderTopWidth": "0px",
                                            "textDecoration": "none",
                                            "borderLeftColor": "rgb(0, 0, 0)",
                                            "borderLeftStyle": "none",
                                            "borderLeftWidth": "0px",
                                            "borderRightColor": "rgb(0, 0, 0)",
                                            "borderRightStyle": "none",
                                            "borderRightWidth": "0px",
                                            "borderBottomColor": "rgb(0, 0, 0)",
                                            "borderBottomStyle": "none",
                                            "borderBottomWidth": "0px",
                                        },
                                    ],
                                },
                            },
                            {
                                "id": "2rpxr7d",
                                "content": {
                                    "type": "text",
                                    "components": [
                                        {
                                            "id": "d0bk1ku",
                                            "text": "Starlit Beauty Salon",
                                            "color": "rgb(0, 0, 0)",
                                            "width": "0px",
                                            "height": "0px",
                                            "padding": "10px 0px 10px 0px",
                                            "fontSize": "14px",
                                            "fontStyle": "normal",
                                            "textAlign": "left",
                                            "fontFamily": "Verdana",
                                            "fontWeight": "bold",
                                            "lineHeight": "1",
                                            "borderRadius": "0px 0px 0px 0px",
                                            "letterSpacing": "0px",
                                            "borderTopColor": "rgb(0, 0, 0)",
                                            "borderTopStyle": "none",
                                            "borderTopWidth": "0px",
                                            "textDecoration": "none",
                                            "borderLeftColor": "rgb(0, 0, 0)",
                                            "borderLeftStyle": "none",
                                            "borderLeftWidth": "0px",
                                            "borderRightColor": "rgb(0, 0, 0)",
                                            "borderRightStyle": "none",
                                            "borderRightWidth": "0px",
                                            "borderBottomColor": "rgb(0, 0, 0)",
                                            "borderBottomStyle": "none",
                                            "borderBottomWidth": "0px",
                                        },
                                    ],
                                },
                            },
                            {
                                "id": "6l4utcc",
                                "content": {
                                    "type": "customValue",
                                    "components": [
                                        {
                                            "id": "dftyze1",
                                            "text": "",
                                            "color": "rgb(0, 0, 0)",
                                            "width": "0px",
                                            "height": "0px",
                                            "padding": "0px 0px 10px 0px",
                                            "fontSize": "14px",
                                            "fontStyle": "normal",
                                            "textAlign": "left",
                                            "fontFamily": "Verdana",
                                            "fontWeight": "bold",
                                            "lineHeight": "1",
                                            "borderRadius": "0px 0px 0px 0px",
                                            "letterSpacing": "0px",
                                            "borderTopColor": "rgb(0, 0, 0)",
                                            "borderTopStyle": "none",
                                            "borderTopWidth": "0px",
                                            "textDecoration": "none",
                                            "borderLeftColor": "rgb(0, 0, 0)",
                                            "borderLeftStyle": "none",
                                            "borderLeftWidth": "0px",
                                            "borderRightColor": "rgb(0, 0, 0)",
                                            "borderRightStyle": "none",
                                            "borderRightWidth": "0px",
                                            "borderBottomColor": "rgb(0, 0, 0)",
                                            "borderBottomStyle": "none",
                                            "borderBottomWidth": "0px",
                                        },
                                        {
                                            "id": "7x4x8fr",
                                            "text":
                                                "3810 Pasadena Ave\nLos Angeles, CA 90031",
                                            "color": "rgb(0, 0, 0)",
                                            "fontSize": "14px",
                                            "fontStyle": "normal",
                                            "textAlign": "left",
                                            "fontFamily": "Arial",
                                            "fontWeight": "normal",
                                            "lineHeight": "1.25",
                                            "letterSpacing": "0px",
                                            "textDecoration": "none",
                                        },
                                    ],
                                },
                            },
                            {
                                "id": "h781zaf",
                                "content": {
                                    "type": "phone",
                                    "components": [
                                        {
                                            "id": "l4sbyns",
                                            "text": "",
                                            "type": "text",
                                            "color": "rgb(0, 0, 0)",
                                            "width": "0px",
                                            "height": "0px",
                                            "padding": "0px 0px 5px 0px",
                                            "fontSize": "14px",
                                            "fontStyle": "normal",
                                            "textAlign": "left",
                                            "fontFamily": "Arial",
                                            "fontWeight": "normal",
                                            "lineHeight": "1",
                                            "letterSpacing": "0px",
                                            "textDecoration": "none",
                                        },
                                        {
                                            "id": "ww85xs4",
                                            "text": "+1 123 456 7890",
                                            "type": "phoneLink",
                                            "color": "rgb(0, 0, 0)",
                                            "fontSize": "14px",
                                            "fontStyle": "normal",
                                            "textAlign": "left",
                                            "fontFamily": "Arial",
                                            "fontWeight": "normal",
                                            "lineHeight": "1",
                                            "letterSpacing": "0px",
                                            "textDecoration": "none",
                                        },
                                    ],
                                },
                            },
                            {
                                "id": "t8cslvu",
                                "content": {
                                    "type": "email",
                                    "components": [
                                        {
                                            "id": "4gclq36",
                                            "text": "",
                                            "type": "text",
                                            "color": "rgb(0, 0, 0)",
                                            "width": "0px",
                                            "height": "0px",
                                            "padding": "0px 0px 10px 0px",
                                            "fontSize": "20px",
                                            "fontStyle": "normal",
                                            "textAlign": "left",
                                            "fontFamily": "Verdana",
                                            "fontWeight": "bold",
                                            "lineHeight": "1",
                                            "letterSpacing": "0px",
                                            "textDecoration": "none",
                                        },
                                        {
                                            "id": "17pnif8",
                                            "text": "example@email.com",
                                            "type": "emailLink",
                                            "color": "rgb(0, 0, 0)",
                                            "fontSize": "14px",
                                            "fontStyle": "normal",
                                            "fontFamily": "Arial",
                                            "fontWeight": "normal",
                                            "lineHeight": "1",
                                            "letterSpacing": "0px",
                                            "textDecoration": "none",
                                        },
                                    ],
                                },
                            },
                            {
                                "id": "4hhx81q",
                                "content": {
                                    "type": "website",
                                    "components": [
                                        {
                                            "id": "mo1xe6d",
                                            "text": "Visit our ",
                                            "type": "text",
                                            "color": "rgb(0, 0, 0)",
                                            "width": "0px",
                                            "height": "0px",
                                            "padding": "0px 0px 0px 0px",
                                            "fontSize": "14px",
                                            "fontStyle": "normal",
                                            "textAlign": "left",
                                            "fontFamily": "Arial",
                                            "fontWeight": "bold",
                                            "lineHeight": "1",
                                            "letterSpacing": "0px",
                                            "textDecoration": "none",
                                        },
                                        {
                                            "id": "6zlcu1c",
                                            "link": "https://www.example.com",
                                            "text": "Instagram",
                                            "type": "websiteLink",
                                            "color": "rgb(65, 26, 138)",
                                            "fontSize": "14px",
                                            "fontStyle": "normal",
                                            "textAlign": "left",
                                            "fontFamily": "Arial",
                                            "fontWeight": "bold",
                                            "lineHeight": "1",
                                            "letterSpacing": "0px",
                                            "textDecoration": "underline",
                                        },
                                    ],
                                },
                            },
                        ],
                        "style": {
                            "width": "auto",
                            "height": "auto",
                            "padding": "15px 10px 15px 0px",
                            "borderRadius": "0px 0px 0px 0px",
                            "verticalAlign": "top",
                            "borderTopColor": "rgb(0, 0, 0)",
                            "borderTopStyle": "none",
                            "borderTopWidth": "0px",
                            "backgroundColor": "rgb(241, 225, 250)",
                            "borderLeftColor": "rgb(0, 0, 0)",
                            "borderLeftStyle": "none",
                            "borderLeftWidth": "0px",
                            "borderRightColor": "rgb(0, 0, 0)",
                            "borderRightStyle": "none",
                            "borderRightWidth": "0px",
                            "borderBottomColor": "rgb(0, 0, 0)",
                            "borderBottomStyle": "none",
                            "borderBottomWidth": "0px",
                        },
                    },
                ],
            },
        ],
    };
};
