import { generateRandomId } from "../utils/generateRandomId";

const getLocalizedContent = () => {
    return {
        name: "Trenton Morrison ",
        title: "accountant",
        phonePrefix: "tel: ",
        phoneValue: "+1 123 456 7890",
        emailPrefix: "email: ",
        emailValue: "example@email.com",
        addressPrefix: "address: ",
        address1: "742 Desert Sun Blvd, Phoenix, AZ",
        availablePrefix: "available: ",
        availableValue: "Mon-Fri, 8 AM - 5 PM",
    };
};

export const signature_g = () => {
    const localizedContent = getLocalizedContent();
    return {
        info: {
            templateSlug: "signature-g",
            version: "0.1",
            name: "Signature G",
        },
        colors: [
            "rgb(54, 54, 54)",
            "rgb(0, 0, 0)",
            "rgb(51, 150, 125)",
        ],
        "dimensions": {
            "spaces": ["15", "10", "5", "7"],
            "corners": [],
            "borders": ["4"],
            "lengths": [],
        },
        rows: [
            {
                id: generateRandomId(),
                columns: [
                    {
                        id: generateRandomId(),
                        rows: [
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "customValue",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.name,
                                            type: "customValue",
                                            color: "rgb(51, 150, 125)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "5px 0px 10px 0px",
                                            fontSize: "20px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                            whiteSpace: "nowrap",
                                        },
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.title,
                                            type: "customValue",
                                            color: "rgb(54, 54, 54)",
                                            fontSize: "16px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "bold",
                                            lineHeight: "1",
                                            letterSpacing: "0px",
                                            textDecoration: "none",
                                            whiteSpace: "nowrap",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "phone",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.phonePrefix,
                                            type: "text",
                                            color: "rgb(54, 54, 54)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 7px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                            whiteSpace: "nowrap",
                                        },
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.phoneValue,
                                            type: "phoneLink",
                                            color: "rgb(0, 0, 0)",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            letterSpacing: "0px",
                                            textDecoration: "none",
                                            whiteSpace: "nowrap",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "email",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.emailPrefix,
                                            type: "text",
                                            color: "rgb(54, 54, 54)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 7px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                            whiteSpace: "nowrap",
                                        },
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.emailValue,
                                            type: "emailLink",
                                            color: "rgb(0, 0, 0)",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            letterSpacing: "0px",
                                            textDecoration: "none",
                                            whiteSpace: "nowrap",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "customValue",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text:
                                                localizedContent.addressPrefix,
                                            type: "text",
                                            color: "rgb(54, 54, 54)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 5px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                            whiteSpace: "nowrap",
                                        },
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.address1,
                                            type: "text",
                                            color: "rgb(0, 0, 0)",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            letterSpacing: "0px",
                                            textDecoration: "none",
                                            whiteSpace: "nowrap",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "customValue",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent
                                                .availablePrefix,
                                            type: "text",
                                            color: "rgb(54, 54, 54)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 5px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                            whiteSpace: "nowrap",
                                        },
                                        {
                                            id: generateRandomId(),
                                            text:
                                                localizedContent.availableValue,
                                            type: "text",
                                            color: "rgb(0, 0, 0)",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            letterSpacing: "0px",
                                            textDecoration: "none",
                                            whiteSpace: "nowrap",
                                        },
                                    ],
                                },
                            },
                        ],
                        style: {
                            padding: "0px 0px 0px 15px",
                            borderRadius: "0px 0px 0px 0px",
                            verticalAlign: "top",
                            borderTopColor: "rgb(0, 0, 0)",
                            borderTopStyle: "none",
                            borderTopWidth: "0px",
                            borderLeftColor: "rgb(51, 150, 125)",
                            borderLeftStyle: "solid",
                            borderLeftWidth: "4px",
                            borderRightColor: "rgb(0, 0, 0)",
                            borderRightStyle: "none",
                            borderRightWidth: "0px",
                            borderBottomColor: "rgb(0, 0, 0)",
                            borderBottomStyle: "none",
                            borderBottomWidth: "0px",
                        },
                    },
                ],
            },
        ],
    };
};
