import { generateRandomId } from "../utils/generateRandomId";
import { content } from "./constants";

const getLocalizedContent = () => {
  return {
    [content.bestRegards]: "Best regards,",
    [content.name]: "Emily Sullivan",
    [content.place]: "Dreamweaver Weddings",
    [content.title]: "Wedding Planner",
    [content.phonePrefix]: "p: ",
    [content.phone]: "+1 123 456 7890",
    [content.email]: "example@email.com",
    [content.emailPrefix]: "e: ",
    [content.websitePrefix]: "w: ",
    [content.website]: "example.com",
    [content.websiteLink]: "example.com",
    [content.address]: "987 Willow Street, Asheville",
    [content.address2]: "NC 28801",
  };
};

export const signature_a = () => {
  const localizedContent = getLocalizedContent();
  return {
    info: {
      templateSlug: "signature-a",
      version: "0.1",
      name: "Signature A",
    },
    "colors": ["rgb(0, 0, 0)", "rgb(81, 25, 92)", "rgb(239,   195, 247)"],
    "dimensions": {
      "spaces": ["10", "5", "3"],
      "corners": ["10"],
      "borders": [],
      "lengths": [],
    },
    "rows": [
      {
        "id": generateRandomId(),
        "columns": [
          {
            "id": generateRandomId(),
            "rows": [
              {
                "id": generateRandomId(),
                "content": {
                  "type": "text",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": localizedContent[content.bestRegards],
                      "type": "text",
                      "color": "rgb(0, 0, 0)",
                      "padding": "0px 0px 10px 0px",
                      "fontSize": "16px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Arial",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "borderRadius": "0px 0px 0px 0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                      "whiteSpace": "nowrap",
                    },
                  ],
                },
              },
            ],
          },
        ],
      },
      {
        "id": generateRandomId(),
        "columns": [
          {
            "id": generateRandomId(),
            "rows": [
              {
                "id": generateRandomId(),
                "content": {
                  "type": "image",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "src":
                        `https://${process.env.NEXT_PUBLIC_AWS_S3_BUCKET_NAME}.s3.${process.env.NEXT_PUBLIC_AWS_REGION}.amazonaws.com/examples/signature_a_preview.png`,
                      "width": "0px",
                      "height": "0px",
                      "margin": "0 auto 0 0",
                      "padding": "0px 0px 0px 0px",
                      "originalSrc":
                        `https://${process.env.NEXT_PUBLIC_AWS_S3_BUCKET_NAME}.s3.${process.env.NEXT_PUBLIC_AWS_REGION}.amazonaws.com/examples/signature_a_original.jpg`,
                      "borderRadius": "0px",
                      "previewWidth": 110,
                      "imageSettings": {
                        "crop": {
                          "x": 27.76039865281848,
                          "y": 17.159029112921832,
                          "unit": "%",
                          "width": 45.228589375813755,
                          "height": 63.93186993069126,
                        },
                        "aspect": "free",
                        "isCircular": false,
                        "borderRadius": {
                          "topLeft": 10,
                          "topRight": 10,
                          "bottomLeft": 10,
                          "bottomRight": 10,
                        },
                      },
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                    },
                  ],
                },
              },
            ],
            "style": {
              "width": "auto",
              "height": "auto",
              "padding": "10px 10px 10px 10px",
              "borderRadius": "10px 0px 0px 10px",
              "verticalAlign": "middle",
              "borderTopColor": "rgb(0, 0, 0)",
              "borderTopStyle": "none",
              "borderTopWidth": "0px",
              "backgroundColor": "rgb(239, 195, 247)",
              "borderLeftColor": "rgb(0, 0, 0)",
              "borderLeftStyle": "none",
              "borderLeftWidth": "0px",
              "borderRightColor": "rgb(0, 0, 0)",
              "borderRightStyle": "none",
              "borderRightWidth": "0px",
              "borderBottomColor": "rgb(0, 0, 0)",
              "borderBottomStyle": "none",
              "borderBottomWidth": "0px",
            },
          },
          {
            "id": generateRandomId(),
            "rows": [
              {
                "id": generateRandomId(),
                "content": {
                  "type": "text",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": localizedContent[content.name],
                      "type": "text",
                      "color": "rgb(81, 25, 92)",
                      "padding": "0px 0px 0px 0px",
                      "fontSize": "16px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Arial",
                      "fontWeight": "bold",
                      "lineHeight": "1",
                      "borderRadius": "0",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(81, 25, 92)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                      "whiteSpace": "nowrap",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "text",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": localizedContent[content.title],
                      "type": "text",
                      "color": "rgb(81, 25, 92)",
                      "padding": "5px 0px 0px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Arial",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "borderRadius": "0px 0px 0px 0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                      "whiteSpace": "nowrap",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "phone",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": localizedContent[content.phonePrefix],
                      "type": "text",
                      "color": "rgb(81, 25, 92)",
                      "padding": "10px 0px 0px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Arial",
                      "fontWeight": "bold",
                      "lineHeight": "1",
                      "borderRadius": "0px 0px 0px 0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                      "whiteSpace": "nowrap",
                    },
                    {
                      "id": generateRandomId(),
                      "text": localizedContent[content.phone],
                      "type": "phoneLink",
                      "color": "rgb(81, 25, 92)",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Arial",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "letterSpacing": "0px",
                      "textDecoration": "none",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "email",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": localizedContent[content.emailPrefix],
                      "type": "text",
                      "color": "rgb(81, 25, 92)",
                      "padding": "3px 0px 0px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Arial",
                      "fontWeight": "bold",
                      "lineHeight": "1",
                      "borderRadius": "0px 0px 0px 0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                      "whiteSpace": "nowrap",
                    },
                    {
                      "id": generateRandomId(),
                      "text": localizedContent[content.email],
                      "type": "emailLink",
                      "color": "rgb(81, 25, 92)",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "fontFamily": "Arial",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "letterSpacing": "0px",
                      "textDecoration": "none",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "website",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": localizedContent[content.websitePrefix],
                      "type": "text",
                      "color": "rgb(81, 25, 92)",
                      "width": "0px",
                      "height": "0px",
                      "padding": "3px 0px 0px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Arial",
                      "fontWeight": "bold",
                      "lineHeight": "1",
                      "borderRadius": "0px 0px 0px 0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                      "whiteSpace": "nowrap",
                    },
                    {
                      "id": generateRandomId(),
                      "link": localizedContent[content.websiteLink],
                      "text": localizedContent[content.website],
                      "type": "websiteLink",
                      "color": "rgb(81, 25, 92)",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Arial",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "letterSpacing": "0px",
                      "textDecoration": "none",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "text",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": localizedContent[content.place],
                      "type": "text",
                      "color": "rgb(81, 25, 92)",
                      "padding": "10px 0px 0px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Arial",
                      "fontWeight": "bold",
                      "lineHeight": "1",
                      "borderRadius": "0px 0px 0px 0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                      "whiteSpace": "nowrap",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "text",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": localizedContent[content.address],
                      "type": "text",
                      "color": "rgb(81, 25, 92)",
                      "padding": "3px 0px 0px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Arial",
                      "fontWeight": "normal",
                      "lineHeight": "1.1",
                      "borderRadius": "0px 0px 0px 0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                      "whiteSpace": "nowrap",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "text",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": localizedContent[content.address2],
                      "color": "rgb(81, 25, 92)",
                      "width": "0px",
                      "height": "0px",
                      "padding": "0px 0px 0px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Arial",
                      "fontWeight": "normal",
                      "lineHeight": "1.1",
                      "borderRadius": "0px 0px 0px 0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                      "whiteSpace": "nowrap",
                    },
                  ],
                },
              },
            ],
            "style": {
              "width": "auto",
              "height": "auto",
              "padding": "10px 10px 10px 0px",
              "borderRadius": "0px 10px 10px 0px",
              "verticalAlign": "middle",
              "borderTopColor": "rgb(0, 0, 0)",
              "borderTopStyle": "none",
              "borderTopWidth": "0px",
              "backgroundColor": "rgb(239, 195, 247)",
              "borderLeftColor": "rgb(0, 0, 0)",
              "borderLeftStyle": "none",
              "borderLeftWidth": "0px",
              "borderRightColor": "rgb(0, 0, 0)",
              "borderRightStyle": "none",
              "borderRightWidth": "0px",
              "borderBottomColor": "rgb(0, 0, 0)",
              "borderBottomStyle": "none",
              "borderBottomWidth": "0px",
            },
          },
        ],
      },
    ],
  };
};
