import { generateRandomId } from "../utils/generateRandomId";
import { content } from "./constants";

const getLocalizedContent = () => {
    return {
        [content.name]: "Michael Carter ⚡",
        [content.title]: "Electrician & Owner",
        [content.phonePrefix]: "phone: ",
        [content.phone]: "+1 123 456 7890",
        [content.emailPrefix]: "email: ",
        [content.email]: "example@email.com",
        [content.availablePrefix]: "available: ",
        [content.availableValue]: "Mon-Fri, 9 AM - 5 PM",
    };
};

export const signature_h = () => {
    const localizedContent = getLocalizedContent();
    return {
        info: {
            templateSlug: "signature-h",
            version: "0.1",
            name: "Signature H",
        },
        colors: [
            "rgb(68, 64, 60)",
            "rgb(59, 59, 59)",
            "rgb(0, 0, 0)",
        ],
        "dimensions": {
            "spaces": ["7", "5"],
            "corners": [],
            "borders": ["3"],
            "lengths": [],
        },
        rows: [
            {
                id: generateRandomId(),
                columns: [
                    {
                        id: generateRandomId(),
                        rows: [
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "text",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text:
                                                localizedContent[content.name],
                                            color: "rgb(0, 0, 0)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 5px 0px",
                                            fontSize: "18px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Verdana",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                            whiteSpace: "nowrap",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "text",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text:
                                                localizedContent[content.title],
                                            color: "rgb(68, 64, 60)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 7px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Verdana",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "solid",
                                            borderBottomWidth: "3px",
                                            whiteSpace: "nowrap",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "phone",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent[
                                                content.phonePrefix
                                            ],
                                            type: "text",
                                            color: "rgb(59, 59, 59)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "7px 0px 0px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Verdana",
                                            fontWeight: "bold",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                            whiteSpace: "nowrap",
                                        },
                                        {
                                            id: generateRandomId(),
                                            text:
                                                localizedContent[content.phone],
                                            type: "phoneLink",
                                            color: "rgb(68, 64, 60)",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1.5",
                                            letterSpacing: "0px",
                                            textDecoration: "none",
                                            whiteSpace: "nowrap",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "email",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent[
                                                content.emailPrefix
                                            ],
                                            type: "text",
                                            color: "rgb(59, 59, 59)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 0px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Verdana",
                                            fontWeight: "bold",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                            whiteSpace: "nowrap",
                                        },
                                        {
                                            id: generateRandomId(),
                                            text:
                                                localizedContent[content.email],
                                            type: "emailLink",
                                            color: "rgb(68, 64, 60)",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1.5",
                                            letterSpacing: "0px",
                                            textDecoration: "none",
                                            whiteSpace: "nowrap",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "twoPartText",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent[
                                                content.availablePrefix
                                            ],
                                            type: "text",
                                            color: "rgb(59, 59, 59)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 0px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Verdana",
                                            fontWeight: "bold",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                            whiteSpace: "nowrap",
                                        },
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent[
                                                content.availableValue
                                            ],
                                            type: "twoPartText",
                                            color: "rgb(68, 64, 60)",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1.5",
                                            letterSpacing: "0px",
                                            textDecoration: "none",
                                            whiteSpace: "nowrap",
                                        },
                                    ],
                                },
                            },
                        ],
                        style: {
                            verticalAlign: "top",
                        },
                    },
                ],
            },
        ],
    };
};
