import { generateRandomId } from "../utils/generateRandomId";

const getLocalizedContent = () => {
  return {
    "best_regards": "Best regards,",
    "name": "Dr. Emily Sullivan",
    "place": "NewDawn Medical Center",
    "title": "Pediatrician",
    "phone": "+1 123 456 7890",
    "email": "example@email.com",
    "address": "987 Willow Street, Asheville",
  };
};

export const signature_a = () => {
  const localizedContent = getLocalizedContent();
  return {
    info: {
      templateSlug: "signature-a",
      version: "0.1",
      name: "Signature A",
    },
    "colors": ["rgb(0, 0, 0)", "rgb(81, 25, 92)", "rgb(239, 195, 247)"],

    "rows": [
      {
        "id": generateRandomId(),
        "columns": [
          {
            "id": generateRandomId(),
            "rows": [
              {
                "id": generateRandomId(),
                "content": {
                  "type": "text",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": localizedContent.best_regards,
                      "type": "text",
                      "color": "rgb(0, 0, 0)",
                      "padding": "0px 0px 10px 0px",
                      "fontSize": "16px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Arial",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "borderRadius": "0px 0px 0px 0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                    },
                  ],
                },
              },
            ],
          },
        ],
      },
      {
        "id": generateRandomId(),
        "columns": [
          {
            "id": generateRandomId(),
            "rows": [
              {
                "id": generateRandomId(),
                "content": {
                  "type": "image",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "src":
                        "https://siph-dev-kfdh6.s3.us-east-1.amazonaws.com/5059b16b-4891-444a-80e9/b382970e/7nycn89.png",
                      "padding": "0px 0px 0px 0px",
                      "originalSrc":
                        "https://siph-dev-kfdh6.s3.us-east-1.amazonaws.com/5059b16b-4891-444a-80e9/b382970e/7nycn89-76mm.jpg",
                      "borderRadius": "0px",
                      "previewWidth": 100,
                      "imageSettings": {
                        "crop": {
                          "x": 24.510680824226664,
                          "y": 0,
                          "unit": "%",
                          "width": 48.751220380386876,
                          "height": 84.38510632310548,
                        },
                        "aspect": "free",
                        "isCircular": false,
                        "borderRadius": 10,
                      },
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                    },
                  ],
                },
              },
            ],
            "style": {
              "padding": "15px 15px 15px 15px",
              "borderRadius": "10px 0px 0px 10px",
              "verticalAlign": "top",
              "borderTopColor": "rgb(0, 0, 0)",
              "borderTopStyle": "none",
              "borderTopWidth": "0px",
              "backgroundColor": "rgb(239, 195, 247)",
              "borderLeftColor": "rgb(0, 0, 0)",
              "borderLeftStyle": "none",
              "borderLeftWidth": "0px",
              "borderRightColor": "rgb(0, 0, 0)",
              "borderRightStyle": "none",
              "borderRightWidth": "0px",
              "borderBottomColor": "rgb(0, 0, 0)",
              "borderBottomStyle": "none",
              "borderBottomWidth": "0px",
            },
          },
          {
            "id": generateRandomId(),
            "rows": [
              {
                "id": generateRandomId(),
                "content": {
                  "type": "text",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": localizedContent.name,
                      "type": "text",
                      "color": "rgb(81, 25, 92)",
                      "padding": "0px 0px 0px 0px",
                      "fontSize": "16px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "bold",
                      "lineHeight": "1",
                      "borderRadius": "0",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(81, 25, 92)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "text",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": localizedContent.title,
                      "type": "text",
                      "color": "rgb(81, 25, 92)",
                      "padding": "5px 0px 0px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "borderRadius": "0px 0px 0px 0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "phone",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": "tel: ",
                      "type": "text",
                      "color": "rgb(81, 25, 92)",
                      "padding": "10px 0px 0px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "bold",
                      "lineHeight": "1",
                      "borderRadius": "0px 0px 0px 0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                    },
                    {
                      "id": generateRandomId(),
                      "text": localizedContent.phone,
                      "type": "phoneLink",
                      "color": "rgb(81, 25, 92)",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Arial",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "letterSpacing": "0px",
                      "textDecoration": "none",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "email",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": "email: ",
                      "type": "text",
                      "color": "rgb(81, 25, 92)",
                      "padding": "5px 0px 0px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "bold",
                      "lineHeight": "1",
                      "borderRadius": "0px 0px 0px 0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                    },
                    {
                      "id": generateRandomId(),
                      "text": localizedContent.email,
                      "type": "emailLink",
                      "color": "rgb(81, 25, 92)",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "fontFamily": "Arial",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "letterSpacing": "0px",
                      "textDecoration": "none",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "text",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": localizedContent.place + "\n",
                      "type": "text",
                      "color": "rgb(81, 25, 92)",
                      "padding": "10px 0px 0px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Verdana",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "borderRadius": "0px 0px 0px 0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                    },
                  ],
                },
              },
              {
                "id": generateRandomId(),
                "content": {
                  "type": "text",
                  "components": [
                    {
                      "id": generateRandomId(),
                      "text": localizedContent.address,
                      "type": "text",
                      "color": "rgb(81, 25, 92)",
                      "padding": "5px 0px 0px 0px",
                      "fontSize": "14px",
                      "fontStyle": "normal",
                      "textAlign": "left",
                      "fontFamily": "Arial",
                      "fontWeight": "normal",
                      "lineHeight": "1",
                      "borderRadius": "0px 0px 0px 0px",
                      "letterSpacing": "0px",
                      "borderTopColor": "rgb(0, 0, 0)",
                      "borderTopStyle": "none",
                      "borderTopWidth": "0px",
                      "textDecoration": "none",
                      "borderLeftColor": "rgb(0, 0, 0)",
                      "borderLeftStyle": "none",
                      "borderLeftWidth": "0px",
                      "borderRightColor": "rgb(0, 0, 0)",
                      "borderRightStyle": "none",
                      "borderRightWidth": "0px",
                      "borderBottomColor": "rgb(0, 0, 0)",
                      "borderBottomStyle": "none",
                      "borderBottomWidth": "0px",
                    },
                  ],
                },
              },
            ],
            "style": {
              "padding": "15px 15px 15px 0px",
              "borderRadius": "0px 10px 10px 0px",
              "verticalAlign": "top",
              "borderTopColor": "rgb(0, 0, 0)",
              "borderTopStyle": "none",
              "borderTopWidth": "0px",
              "backgroundColor": "rgb(239, 195, 247)",
              "borderLeftColor": "rgb(0, 0, 0)",
              "borderLeftStyle": "none",
              "borderLeftWidth": "0px",
              "borderRightColor": "rgb(0, 0, 0)",
              "borderRightStyle": "none",
              "borderRightWidth": "0px",
              "borderBottomColor": "rgb(0, 0, 0)",
              "borderBottomStyle": "none",
              "borderBottomWidth": "0px",
            },
          },
        ],
      },
    ],
  };
};
