export const signature_b = {
    info: {
        templateSlug: "signature-b",
        version: "0.1",
        name: "Signature b",
    },

    colors: [
        "rgb(58, 135, 176)",
    ],
    rows: [
        {
            id: "qvz6jx4",
            columns: [
                {
                    id: "2g94egx",
                    rows: [
                        {
                            id: "02605w9",
                            content: {
                                type: "image",
                                components: [
                                    {
                                        id: "czkoydq",
                                        src: "https://signatures-photos-dev.s3.us-east-1.amazonaws.com/examples/signature_b_preview.png",
                                        padding: "0px 0px 0px 0px",
                                        originalSrc:
                                            "https://signatures-photos-dev.s3.us-east-1.amazonaws.com/examples/signature_b_original.png",
                                        borderRadius: "0px",
                                        previewWidth: 120,
                                        imageSettings: {
                                            crop: {
                                                x: 27.195619931183135,
                                                y: 0.6912433092844557,
                                                unit: "%",
                                                width: 45.908577597899594,
                                                height: 30.60591607675713,
                                            },
                                            aspect: 1,
                                            isCircular: true,
                                            borderRadius: 0,
                                        },
                                    },
                                ],
                            },
                        },
                    ],
                },
                {
                    id: "vd9awmu",
                    rows: [
                        {
                            id: "2584npj",
                            content: {
                                type: "text",
                                components: [
                                    {
                                        id: "7izd7ue",
                                        text: "Madison Brooks",
                                        color: "rgb(0, 0, 0)",
                                        padding: "0px 0px 0px 0px",
                                        fontSize: "17px",
                                        fontStyle: "normal",
                                        textAlign: "left",
                                        fontFamily: "Verdana",
                                        fontWeight: "normal",
                                        lineHeight: "1",
                                        borderRadius: "0",
                                        letterSpacing: "0",
                                        textDecoration: "none",
                                    },
                                ],
                            },
                        },
                        {
                            id: "rgd9sky",
                            content: {
                                type: "text",
                                components: [
                                    {
                                        id: "wsf7zcr",
                                        text: "Professional Photographer",
                                        color: "rgb(0, 0, 0)",
                                        padding: "5px 0px 5px 0px",
                                        fontSize: "14px",
                                        fontStyle: "normal",
                                        textAlign: "left",
                                        fontFamily: "Verdana",
                                        fontWeight: "normal",
                                        lineHeight: "1",
                                        borderRadius: "0px",
                                        letterSpacing: "0",
                                        textDecoration: "none",
                                    },
                                ],
                            },
                        },
                        {
                            id: "95fhzym",
                            content: {
                                type: "phone",
                                components: [
                                    {
                                        id: "x4jmoip",
                                        text: "tel: ",
                                        type: "text",
                                        color: "rgb(58, 135, 176)",
                                        padding: "0px 0px 0px 0px",
                                        fontSize: "14px",
                                        fontStyle: "normal",
                                        textAlign: "left",
                                        fontFamily: "Verdana",
                                        fontWeight: "normal",
                                        lineHeight: "1",
                                        borderRadius: "0px",
                                        letterSpacing: "0",
                                        textDecoration: "none",
                                    },
                                    {
                                        id: "pnu7bpr",
                                        text: "+1 123 456 7890 ",
                                        type: "phoneLink",
                                        color: "rgb(0, 0, 0)",
                                        fontSize: "14px",
                                        fontStyle: "normal",
                                        textAlign: "left",
                                        fontFamily: "Verdana",
                                        fontWeight: "normal",
                                        lineHeight: "1.25",
                                        letterSpacing: "0",
                                        textDecoration: "none",
                                    },
                                ],
                            },
                        },
                        {
                            id: "nnushns",
                            content: {
                                type: "email",
                                components: [
                                    {
                                        id: "dfxvz36",
                                        text: "email: ",
                                        type: "text",
                                        color: "rgb(58, 135, 176)",
                                        padding: "0px 0px 0px 0px",
                                        fontSize: "14px",
                                        fontStyle: "normal",
                                        textAlign: "left",
                                        fontFamily: "Verdana",
                                        fontWeight: "normal",
                                        lineHeight: "1",
                                        borderRadius: "0",
                                        letterSpacing: "0",
                                        textDecoration: "none",
                                    },
                                    {
                                        id: "4n3dbwt",
                                        text: "example@email.com",
                                        type: "emailLink",
                                        color: "rgb(0, 0, 0)",
                                        fontSize: "14px",
                                        fontStyle: "normal",
                                        textAlign: "left",
                                        fontFamily: "Verdana",
                                        fontWeight: "normal",
                                        lineHeight: "1.25",
                                        letterSpacing: "0",
                                        textDecoration: "none",
                                    },
                                ],
                            },
                        },
                        {
                            id: "egz7qh7",
                            content: {
                                type: "website",
                                components: [
                                    {
                                        id: "zthde6i",
                                        text: "web: ",
                                        type: "text",
                                        color: "rgb(58, 135, 176)",
                                        padding: "0px 0px 0px 0px",
                                        fontSize: "14px",
                                        fontStyle: "normal",
                                        textAlign: "left",
                                        fontFamily: "Verdana",
                                        fontWeight: "normal",
                                        lineHeight: "1",
                                        borderRadius: "0px",
                                        letterSpacing: "0",
                                        textDecoration: "none",
                                    },
                                    {
                                        id: "aqok9fw",
                                        text: "www.example.com",
                                        type: "websiteLink",
                                        color: "rgb(0, 0, 0)",
                                        fontSize: "14px",
                                        fontStyle: "normal",
                                        textAlign: "left",
                                        fontFamily: "Verdana",
                                        fontWeight: "normal",
                                        lineHeight: "1.25",
                                        letterSpacing: "0",
                                        textDecoration: "none",
                                    },
                                ],
                            },
                        },
                    ],
                    style: {
                        padding: "0px 0px 0px 10px",
                        borderRadius: "0px",
                        verticalAlign: "middle",
                        borderTopColor: "rgb(0, 0, 0)",
                        borderTopStyle: "none",
                        borderTopWidth: "0",
                        borderLeftColor: "rgb(0, 0, 0)",
                        borderLeftStyle: "none",
                        borderLeftWidth: "0",
                        borderRightColor: "rgb(0, 0, 0)",
                        borderRightStyle: "none",
                        borderRightWidth: "0",
                        borderBottomColor: "rgb(0, 0, 0)",
                        borderBottomStyle: "none",
                        borderBottomWidth: "0",
                    },
                },
            ],
        },
    ],
};
