import { generateRandomId } from "../utils/generateRandomId";

const getLocalizedContent = () => {
    return {
        name: "Michael Carter ",
        title: "Electrician & Owner",
        phonePrefix: "phone: ",
        phoneValue: "+1 123 456 7890",
        emailPrefix: "email: ",
        emailValue: "example@email.com",
        availablePrefix: "available: ",
        availableValue: "Mon-Fri, 9 AM - 5 PM",
    };
};

export const signature_h = () => {
    const localizedContent = getLocalizedContent();
    return {
        info: {
            templateSlug: "signature-h",
            version: "0.1",
            name: "Signature H",
        },
        colors: [
            "rgb(68, 64, 60)",
            "rgb(59, 59, 59)",
        ],
        rows: [
            {
                id: generateRandomId(),
                columns: [
                    {
                        id: generateRandomId(),
                        rows: [
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "text",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.name,
                                            color: "rgb(0, 0, 0)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 5px 0px",
                                            fontSize: "18px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Verdana",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "text",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.title,
                                            color: "rgb(68, 64, 60)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 7px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Verdana",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "solid",
                                            borderBottomWidth: "3px",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "phone",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.phonePrefix,
                                            type: "text",
                                            color: "rgb(59, 59, 59)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "7px 0px 0px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Verdana",
                                            fontWeight: "bold",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                        },
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.phoneValue,
                                            type: "phoneLink",
                                            color: "rgb(68, 64, 60)",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1.5",
                                            letterSpacing: "0px",
                                            textDecoration: "none",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "email",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.emailPrefix,
                                            type: "text",
                                            color: "rgb(59, 59, 59)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 0px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Verdana",
                                            fontWeight: "bold",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                        },
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent.emailValue,
                                            type: "emailLink",
                                            color: "rgb(68, 64, 60)",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1.5",
                                            letterSpacing: "0px",
                                            textDecoration: "none",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "customValue",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent
                                                .availablePrefix,
                                            type: "text",
                                            color: "rgb(59, 59, 59)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 0px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Verdana",
                                            fontWeight: "bold",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                        },
                                        {
                                            id: generateRandomId(),
                                            text:
                                                localizedContent.availableValue,
                                            type: "customValue",
                                            color: "rgb(68, 64, 60)",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1.5",
                                            letterSpacing: "0px",
                                            textDecoration: "none",
                                        },
                                    ],
                                },
                            },
                        ],
                        style: {
                            verticalAlign: "top",
                        },
                    },
                ],
            },
        ],
    };
};
