import { generateRandomId } from '../utils/generateRandomId';

export const signature_i = () => {
  return {
    info: {
      templateSlug: 'signature-i',
      version: '0.1',
      name: 'Signature I',
    },
    colors: [
      'rgb(71, 71, 71)',
      'rgb(109, 143, 118)',
      'rgb(204, 120, 43)',
      'rgb(181, 124, 91)',
    ],
    rows: [
      {
        id: generateRandomId(),
        columns: [
          {
            id: generateRandomId(),
            rows: [
              {
                id: generateRandomId(),
                content: {
                  type: 'image',
                  components: [
                    {
                      id: generateRandomId(),
                      src: `https://${process.env.NEXT_PUBLIC_AWS_S3_BUCKET_NAME}.s3.${process.env.NEXT_PUBLIC_AWS_REGION}.amazonaws.com/examples/signature_i_preview.png`,
                      width: '0px',
                      height: '0px',
                      margin: '0 auto 0 0',
                      padding: '0px 0px 0px 0px',
                      originalSrc: `https://${process.env.NEXT_PUBLIC_AWS_S3_BUCKET_NAME}.s3.${process.env.NEXT_PUBLIC_AWS_REGION}.amazonaws.com/examples/signature_i_original.jpg`,
                      borderRadius: '0px 0px 0px 0px',
                      imageSettings: {
                        crop: {
                          x: 17.90408434186663,
                          y: 27.69051940352828,
                          unit: '%',
                          width: 71.62107110401944,
                          height: 50.765597025553376,
                        },
                        aspect: 'free',
                        isCircular: false,
                        borderRadius: {
                          topLeft: 60,
                          topRight: 0,
                          bottomLeft: 0,
                          bottomRight: 60,
                        },
                      },
                      borderTopColor: 'rgb(0, 0, 0)',
                      borderTopStyle: 'none',
                      borderTopWidth: '0px',
                      borderLeftColor: 'rgb(0, 0, 0)',
                      borderLeftStyle: 'none',
                      borderLeftWidth: '0px',
                      borderRightColor: 'rgb(0, 0, 0)',
                      borderRightStyle: 'none',
                      borderRightWidth: '0px',
                      borderBottomColor: 'rgb(0, 0, 0)',
                      borderBottomStyle: 'none',
                      borderBottomWidth: '0px',
                    },
                  ],
                },
              },
            ],
            style: {
              verticalAlign: 'top',
            },
          },
          {
            id: generateRandomId(),
            rows: [
              {
                id: generateRandomId(),
                content: {
                  type: 'text',
                  components: [
                    {
                      id: generateRandomId(),
                      text: 'Adeline Waren',
                      color: 'rgb(204, 120, 43)',
                      width: '0px',
                      height: '0px',
                      padding: '0px 0px 5px 0px',
                      fontSize: '22px',
                      fontStyle: 'normal',
                      textAlign: 'right',
                      fontFamily: 'Arial',
                      fontWeight: 'bold',
                      lineHeight: '1',
                      borderRadius: '0',
                      letterSpacing: '0px',
                      borderTopColor: 'rgb(0, 0, 0)',
                      borderTopStyle: 'none',
                      borderTopWidth: '0px',
                      textDecoration: 'none',
                      borderLeftColor: 'rgb(0, 0, 0)',
                      borderLeftStyle: 'none',
                      borderLeftWidth: '0px',
                      borderRightColor: 'rgb(0, 0, 0)',
                      borderRightStyle: 'none',
                      borderRightWidth: '0px',
                      borderBottomColor: 'rgb(0, 0, 0)',
                      borderBottomStyle: 'none',
                      borderBottomWidth: '0px',
                    },
                  ],
                },
              },
              {
                id: generateRandomId(),
                content: {
                  type: 'text',
                  components: [
                    {
                      id: generateRandomId(),
                      text: 'landscape architect',
                      color: 'rgb(109, 143, 118)',
                      width: '0px',
                      height: '0px',
                      padding: '0px 0px 5px 0px',
                      fontSize: '18px',
                      fontStyle: 'normal',
                      textAlign: 'right',
                      fontFamily: 'Arial',
                      fontWeight: 'bold',
                      lineHeight: '1',
                      borderRadius: '0px 0px 0px 0px',
                      letterSpacing: '0px',
                      borderTopColor: 'rgb(0, 0, 0)',
                      borderTopStyle: 'none',
                      borderTopWidth: '0px',
                      textDecoration: 'none',
                      borderLeftColor: 'rgb(0, 0, 0)',
                      borderLeftStyle: 'none',
                      borderLeftWidth: '0px',
                      borderRightColor: 'rgb(0, 0, 0)',
                      borderRightStyle: 'none',
                      borderRightWidth: '0px',
                      borderBottomColor: 'rgb(0, 0, 0)',
                      borderBottomStyle: 'none',
                      borderBottomWidth: '0px',
                    },
                  ],
                },
              },
              {
                id: generateRandomId(),
                content: {
                  type: 'phone',
                  components: [
                    {
                      id: generateRandomId(),
                      text: '',
                      type: 'text',
                      color: 'rgb(181, 124, 91)',
                      width: '0px',
                      height: '0px',
                      padding: '10px 0px 5px 0px',
                      fontSize: '18px',
                      fontStyle: 'normal',
                      textAlign: 'right',
                      fontFamily: 'Arial',
                      fontWeight: 'bold',
                      lineHeight: '1',
                      borderRadius: '0px 0px 0px 0px',
                      letterSpacing: '0px',
                      borderTopColor: 'rgb(0, 0, 0)',
                      borderTopStyle: 'none',
                      borderTopWidth: '0px',
                      textDecoration: 'none',
                      borderLeftColor: 'rgb(0, 0, 0)',
                      borderLeftStyle: 'none',
                      borderLeftWidth: '0px',
                      borderRightColor: 'rgb(0, 0, 0)',
                      borderRightStyle: 'none',
                      borderRightWidth: '0px',
                      borderBottomColor: 'rgb(0, 0, 0)',
                      borderBottomStyle: 'none',
                      borderBottomWidth: '0px',
                    },
                    {
                      id: generateRandomId(),
                      text: '+1 123 456 7890',
                      type: 'phoneLink',
                      color: 'rgb(71, 71, 71)',
                      fontSize: '14px',
                      fontStyle: 'normal',
                      textAlign: 'right',
                      fontFamily: 'Arial',
                      fontWeight: 'bold',
                      lineHeight: '1',
                      letterSpacing: '0px',
                      textDecoration: 'none',
                    },
                  ],
                },
              },
              {
                id: generateRandomId(),
                content: {
                  type: 'email',
                  components: [
                    {
                      id: generateRandomId(),
                      text: '',
                      type: 'text',
                      color: 'rgb(181, 124, 91)',
                      width: '0px',
                      height: '0px',
                      padding: '0px 0px 5px 0px',
                      fontSize: '18px',
                      fontStyle: 'normal',
                      textAlign: 'right',
                      fontFamily: 'Arial',
                      fontWeight: 'bold',
                      lineHeight: '1',
                      borderRadius: '0px 0px 0px 0px',
                      letterSpacing: '0px',
                      borderTopColor: 'rgb(0, 0, 0)',
                      borderTopStyle: 'none',
                      borderTopWidth: '0px',
                      textDecoration: 'none',
                      borderLeftColor: 'rgb(0, 0, 0)',
                      borderLeftStyle: 'none',
                      borderLeftWidth: '0px',
                      borderRightColor: 'rgb(0, 0, 0)',
                      borderRightStyle: 'none',
                      borderRightWidth: '0px',
                      borderBottomColor: 'rgb(0, 0, 0)',
                      borderBottomStyle: 'none',
                      borderBottomWidth: '0px',
                    },
                    {
                      id: generateRandomId(),
                      text: 'example@email.com',
                      type: 'emailLink',
                      color: 'rgb(71, 71, 71)',
                      fontSize: '14px',
                      fontStyle: 'normal',
                      textAlign: 'right',
                      fontFamily: 'Arial',
                      fontWeight: 'bold',
                      lineHeight: '1',
                      letterSpacing: '0px',
                      textDecoration: 'none',
                    },
                  ],
                },
              },
              {
                id: generateRandomId(),
                content: {
                  type: 'website',
                  components: [
                    {
                      id: generateRandomId(),
                      text: '',
                      type: 'text',
                      color: 'rgb(181, 124, 91)',
                      width: '0px',
                      height: '0px',
                      padding: '0px 0px 0px 0px',
                      fontSize: '18px',
                      fontStyle: 'normal',
                      textAlign: 'right',
                      fontFamily: 'Arial',
                      fontWeight: 'bold',
                      lineHeight: '1',
                      borderRadius: '0px 0px 0px 0px',
                      letterSpacing: '0px',
                      borderTopColor: 'rgb(0, 0, 0)',
                      borderTopStyle: 'none',
                      borderTopWidth: '0px',
                      textDecoration: 'none',
                      borderLeftColor: 'rgb(0, 0, 0)',
                      borderLeftStyle: 'none',
                      borderLeftWidth: '0px',
                      borderRightColor: 'rgb(0, 0, 0)',
                      borderRightStyle: 'none',
                      borderRightWidth: '0px',
                      borderBottomColor: 'rgb(0, 0, 0)',
                      borderBottomStyle: 'none',
                      borderBottomWidth: '0px',
                    },
                    {
                      id: generateRandomId(),
                      text: 'www.example.com',
                      type: 'websiteLink',
                      color: 'rgb(71, 71, 71)',
                      fontSize: '14px',
                      fontStyle: 'normal',
                      textAlign: 'right',
                      fontFamily: 'Arial',
                      fontWeight: 'bold',
                      lineHeight: '1',
                      letterSpacing: '0px',
                      textDecoration: 'none',
                    },
                  ],
                },
              },
            ],
            style: {
              width: '224px',
              height: 'auto',
              padding: '0px 0px 0px 0px',
              borderRadius: '0px 0px 0px 0px',
              verticalAlign: 'middle',
              borderTopColor: 'rgb(0, 0, 0)',
              borderTopStyle: 'none',
              borderTopWidth: '0px',
              borderLeftColor: 'rgb(0, 0, 0)',
              borderLeftStyle: 'none',
              borderLeftWidth: '0px',
              borderRightColor: 'rgb(0, 0, 0)',
              borderRightStyle: 'none',
              borderRightWidth: '0px',
              borderBottomColor: 'rgb(0, 0, 0)',
              borderBottomStyle: 'none',
              borderBottomWidth: '0px',
            },
          },
        ],
      },
      {
        id: generateRandomId(),
        columns: [
          {
            id: generateRandomId(),
            rows: [
              {
                id: generateRandomId(),
                content: {
                  type: 'text',
                  components: [
                    {
                      id: generateRandomId(),
                      text: 'Turning your vision into a stunning landscape reality.',
                      color: 'rgb(71, 71, 71)',
                      width: '343px',
                      height: '0px',
                      padding: '25px 0px 5px 0px',
                      fontSize: '14px',
                      fontStyle: 'italic',
                      textAlign: 'center',
                      fontFamily: 'Arial',
                      fontWeight: 'normal',
                      lineHeight: '1',
                      borderRadius: '0px 0px 0px 0px',
                      letterSpacing: '0px',
                      borderTopColor: 'rgb(0, 0, 0)',
                      borderTopStyle: 'none',
                      borderTopWidth: '0px',
                      textDecoration: 'none',
                      borderLeftColor: 'rgb(0, 0, 0)',
                      borderLeftStyle: 'none',
                      borderLeftWidth: '0px',
                      borderRightColor: 'rgb(0, 0, 0)',
                      borderRightStyle: 'none',
                      borderRightWidth: '0px',
                      borderBottomColor: 'rgb(0, 0, 0)',
                      borderBottomStyle: 'none',
                      borderBottomWidth: '0px',
                    },
                  ],
                },
              },
            ],
          },
        ],
      },
    ],
  };
};
