import { generateRandomId } from "../utils/generateRandomId";
import { content } from "./constants";

const getLocalizedContent = () => {
    return {
        [content.name]: "- James -",
        [content.surname]: "Wilkerson",
        [content.title]: "SOUND PRODUCER",
        [content.phone]: "+1 123 456 7890",
        [content.email]: "example@email.com",
        [content.website]: "www.example.com",
        [content.youtubeText]: "YouTube",
        [content.youtubeLink]: "https://www.youtube.com",
        [content.visitText]: "Visit our ",
    };
};

export const signature_k = () => {
    const localizedContent = getLocalizedContent();
    return {
        info: {
            templateSlug: "signature-k",
            version: "0.1",
            name: "Signature K",
        },
        colors: [
            "rgb(0, 0, 0)",
        ],
        "dimensions": {
            "spaces": ["90", "15", "5"],
            "corners": [],
            "borders": [],
            "lengths": [],
        },
        rows: [
            {
                id: generateRandomId(),
                columns: [
                    {
                        id: generateRandomId(),
                        rows: [
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "text",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text:
                                                localizedContent[content.name],
                                            color: "rgb(0, 0, 0)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 5px 0px",
                                            fontSize: "22px",
                                            fontStyle: "normal",
                                            textAlign: "center",
                                            fontFamily: "Helvetica",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0",
                                            letterSpacing: "3px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                            whiteSpace: "nowrap",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "text",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent[
                                                content.surname
                                            ],
                                            color: "rgb(0, 0, 0)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 5px 0px",
                                            fontSize: "22px",
                                            fontStyle: "normal",
                                            textAlign: "center",
                                            fontFamily: "Helvetica",
                                            fontWeight: "bold",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "3px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                            whiteSpace: "nowrap",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "text",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text:
                                                localizedContent[content.title],
                                            color: "rgb(0, 0, 0)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "5px 0px 0px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Helvetica",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                            whiteSpace: "nowrap",
                                        },
                                    ],
                                },
                            },
                        ],
                        style: {
                            padding: "0px 15px 0px 0px",
                            borderRadius: "0px 0px 0px 0px",
                            verticalAlign: "top",
                            borderTopColor: "rgb(0, 0, 0)",
                            borderTopStyle: "none",
                            borderTopWidth: "0px",
                            borderLeftColor: "rgb(0, 0, 0)",
                            borderLeftStyle: "none",
                            borderLeftWidth: "0px",
                            borderRightColor: "rgb(0, 0, 0)",
                            borderRightStyle: "solid",
                            borderRightWidth: "3px",
                            borderBottomColor: "rgb(0, 0, 0)",
                            borderBottomStyle: "none",
                            borderBottomWidth: "0px",
                        },
                    },
                    {
                        id: generateRandomId(),
                        rows: [
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "phone",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: "",
                                            type: "text",
                                            color: "rgb(0, 0, 0)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 5px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                            whiteSpace: "nowrap",
                                        },
                                        {
                                            id: generateRandomId(),
                                            text:
                                                localizedContent[content.phone],
                                            type: "phoneLink",
                                            color: "rgb(0, 0, 0)",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            letterSpacing: "0px",
                                            textDecoration: "none",
                                            whiteSpace: "nowrap",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "email",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: "",
                                            type: "text",
                                            color: "rgb(0, 0, 0)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 5px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                            whiteSpace: "nowrap",
                                        },
                                        {
                                            id: generateRandomId(),
                                            text:
                                                localizedContent[content.email],
                                            type: "emailLink",
                                            color: "rgb(0, 0, 0)",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            letterSpacing: "0px",
                                            textDecoration: "none",
                                            whiteSpace: "nowrap",
                                        },
                                    ],
                                },
                            },
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "website",
                                    components: [
                                        {
                                            id: generateRandomId(),
                                            text: "",
                                            type: "text",
                                            color: "rgb(0, 0, 0)",
                                            width: "0px",
                                            height: "0px",
                                            padding: "0px 0px 0px 0px",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            textAlign: "left",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            borderRadius: "0px 0px 0px 0px",
                                            letterSpacing: "0px",
                                            borderTopColor: "rgb(0, 0, 0)",
                                            borderTopStyle: "none",
                                            borderTopWidth: "0px",
                                            textDecoration: "none",
                                            borderLeftColor: "rgb(0, 0, 0)",
                                            borderLeftStyle: "none",
                                            borderLeftWidth: "0px",
                                            borderRightColor: "rgb(0, 0, 0)",
                                            borderRightStyle: "none",
                                            borderRightWidth: "0px",
                                            borderBottomColor: "rgb(0, 0, 0)",
                                            borderBottomStyle: "none",
                                            borderBottomWidth: "0px",
                                            whiteSpace: "nowrap",
                                        },
                                        {
                                            id: generateRandomId(),
                                            text: localizedContent[
                                                content.website
                                            ],
                                            type: "websiteLink",
                                            color: "rgb(0, 0, 0)",
                                            fontSize: "14px",
                                            fontStyle: "normal",
                                            fontFamily: "Arial",
                                            fontWeight: "normal",
                                            lineHeight: "1",
                                            letterSpacing: "0px",
                                            textDecoration: "none",
                                            whiteSpace: "nowrap",
                                        },
                                    ],
                                },
                            },
                        ],
                        style: {
                            padding: "0px 0px 0px 15px",
                            borderRadius: "0px 0px 0px 0px",
                            verticalAlign: "middle",
                            borderTopColor: "rgb(0, 0, 0)",
                            borderTopStyle: "none",
                            borderTopWidth: "0px",
                            borderLeftColor: "rgb(0, 0, 0)",
                            borderLeftStyle: "none",
                            borderLeftWidth: "0px",
                            borderRightColor: "rgb(0, 0, 0)",
                            borderRightStyle: "none",
                            borderRightWidth: "0px",
                            borderBottomColor: "rgb(0, 0, 0)",
                            borderBottomStyle: "none",
                            borderBottomWidth: "0px",
                        },
                    },
                ],
            },
            {
                id: generateRandomId(),
                columns: [
                    {
                        id: generateRandomId(),
                        rows: [
                            {
                                id: generateRandomId(),
                                content: {
                                    type: "website",
                                    components: [
                                        {
                                            "id": "zwn32us",
                                            "text": "Visit our ",
                                            "type": "text",
                                            "color": "rgb(0, 0, 0)",
                                            "width": "0px",
                                            "height": "0px",
                                            "padding": "15px 0px 5px 90px",
                                            "fontSize": "16px",
                                            "fontStyle": "normal",
                                            "textAlign": "left",
                                            "fontFamily": "Arial",
                                            "fontWeight": "normal",
                                            "lineHeight": "1",
                                            "borderRadius": "0px 0px 0px 0px",
                                            "letterSpacing": "0px",
                                            "borderTopColor": "rgb(0, 0, 0)",
                                            "borderTopStyle": "none",
                                            "borderTopWidth": "0px",
                                            "textDecoration": "none",
                                            "borderLeftColor": "rgb(0, 0, 0)",
                                            "borderLeftStyle": "none",
                                            "borderLeftWidth": "0px",
                                            "borderRightColor": "rgb(0, 0, 0)",
                                            "borderRightStyle": "none",
                                            "borderRightWidth": "0px",
                                            "borderBottomColor": "rgb(0, 0, 0)",
                                            "borderBottomStyle": "none",
                                            "borderBottomWidth": "0px",
                                            "whiteSpace": "nowrap",
                                        },
                                        {
                                            "id": "l8izwye",
                                            "link": localizedContent[
                                                content.youtubeLink
                                            ],
                                            "text": localizedContent[
                                                content.youtubeText
                                            ],
                                            "type": "websiteLink",
                                            "color": "rgb(0, 0, 0)",
                                            "fontSize": "16px",
                                            "fontStyle": "normal",
                                            "textAlign": "left",
                                            "fontFamily": "Arial",
                                            "fontWeight": "bold",
                                            "lineHeight": "1",
                                            "letterSpacing": "0px",
                                            "textDecoration": "underline",
                                            "whiteSpace": "nowrap",
                                        },
                                    ],
                                },
                            },
                        ],
                        style: {
                            padding: "0px 0px 0px 0px",
                            borderRadius: "0px 0px 0px 0px",
                            verticalAlign: "top",
                            borderTopColor: "rgb(0, 0, 0)",
                            borderTopStyle: "none",
                            borderTopWidth: "0px",
                            borderLeftColor: "rgb(0, 0, 0)",
                            borderLeftStyle: "none",
                            borderLeftWidth: "0px",
                            borderRightColor: "rgb(0, 0, 0)",
                            borderRightStyle: "none",
                            borderRightWidth: "0px",
                            borderBottomColor: "rgb(0, 0, 0)",
                            borderBottomStyle: "none",
                            borderBottomWidth: "0px",
                        },
                    },
                ],
            },
        ],
    };
};
