import { generateRandomId } from "../utils/generateRandomId";

const getLocalizedContent = () => {
    return {
        name: "Mitchell Bartell",
        title: "interior designer",
        phonePrefix: "phone: ",
        phoneValue: "+1 123 456 7890",
        emailPrefix: "email: ",
        emailValue: "example@email.com",
        addressValue: "14439 Annamarie Drives\nEaston, IL 62633",
        websitePrefix: "",
        websiteText: "example.com",
        websiteLink: "https://www.example.com",
    };
};

export const signature_d = () => {
    const localizedContent = getLocalizedContent();
    return {
        "info": {
            templateSlug: "signature-d",
            version: "0.1",
            name: "Signature D",
        },
        "colors": [
            "rgb(0, 0, 0)",
            "rgb(105, 105, 105)",
            "rgb(61, 61, 61)",
        ],
        "rows": [
            {
                "id": generateRandomId(),
                "columns": [
                    {
                        "id": generateRandomId(),
                        "rows": [
                            {
                                "id": generateRandomId(),
                                "content": {
                                    "type": "image",
                                    "components": [
                                        {
                                            "id": generateRandomId(),
                                            "src":
                                                `https://${process.env.NEXT_PUBLIC_AWS_S3_BUCKET_NAME}.s3.${process.env.NEXT_PUBLIC_AWS_REGION}.amazonaws.com/examples/signature_d_preview.png`,
                                            "width": "0px",
                                            "height": "0px",
                                            "margin": "0 auto 0 0",
                                            "padding": "0px 15px 0px 0px",
                                            "originalSrc":
                                                `https://${process.env.NEXT_PUBLIC_AWS_S3_BUCKET_NAME}.s3.${process.env.NEXT_PUBLIC_AWS_REGION}.amazonaws.com/examples/signature_d_original.jpg`,
                                            "borderRadius": "0px 0px 0px 0px",
                                            "previewWidth": 120,
                                            "imageSettings": {
                                                "crop": {
                                                    "x": 16.980004721366498,
                                                    "y": 0,
                                                    "unit": "%",
                                                    "width": 66.48281622468757,
                                                    "height": 96.65676502699263,
                                                },
                                                "aspect": "free",
                                                "isCircular": false,
                                                "borderRadius": {
                                                    "topLeft": 10,
                                                    "topRight": 0,
                                                    "bottomLeft": 10,
                                                    "bottomRight": 0,
                                                },
                                            },
                                            "borderTopColor": "rgb(0, 0, 0)",
                                            "borderTopStyle": "none",
                                            "borderTopWidth": "0px",
                                            "borderLeftColor": "rgb(0, 0, 0)",
                                            "borderLeftStyle": "none",
                                            "borderLeftWidth": "0px",
                                            "borderRightColor": "rgb(0, 0, 0)",
                                            "borderRightStyle": "none",
                                            "borderRightWidth": "0px",
                                            "borderBottomColor": "rgb(0, 0, 0)",
                                            "borderBottomStyle": "none",
                                            "borderBottomWidth": "0px",
                                        },
                                    ],
                                },
                            },
                        ],
                    },
                    {
                        "id": generateRandomId(),
                        "rows": [
                            {
                                "id": generateRandomId(),
                                "content": {
                                    "type": "text",
                                    "components": [
                                        {
                                            "id": generateRandomId(),
                                            "text": localizedContent.name,
                                            "color": "rgb(0, 0, 0)",
                                            "width": "0px",
                                            "height": "0px",
                                            "padding": "0px 0px 5px 0px",
                                            "fontSize": "20px",
                                            "fontStyle": "normal",
                                            "textAlign": "left",
                                            "fontFamily": "Verdana",
                                            "fontWeight": "normal",
                                            "lineHeight": "1",
                                            "borderRadius": "0",
                                            "letterSpacing": "0px",
                                            "borderTopColor": "rgb(0, 0, 0)",
                                            "borderTopStyle": "none",
                                            "borderTopWidth": "0px",
                                            "textDecoration": "none",
                                            "borderLeftColor": "rgb(0, 0, 0)",
                                            "borderLeftStyle": "none",
                                            "borderLeftWidth": "0px",
                                            "borderRightColor": "rgb(0, 0, 0)",
                                            "borderRightStyle": "none",
                                            "borderRightWidth": "0px",
                                            "borderBottomColor": "rgb(0, 0, 0)",
                                            "borderBottomStyle": "none",
                                            "borderBottomWidth": "0px",
                                        },
                                    ],
                                },
                            },
                            {
                                "id": generateRandomId(),
                                "content": {
                                    "type": "text",
                                    "components": [
                                        {
                                            "id": generateRandomId(),
                                            "text": localizedContent.title,
                                            "color": "rgb(105, 105, 105)",
                                            "width": "0px",
                                            "height": "0px",
                                            "padding": "0px 0px 10px 0px",
                                            "fontSize": "16px",
                                            "fontStyle": "normal",
                                            "textAlign": "left",
                                            "fontFamily": "Verdana",
                                            "fontWeight": "normal",
                                            "lineHeight": "1",
                                            "borderRadius": "0px 0px 0px 0px",
                                            "letterSpacing": "0px",
                                            "borderTopColor": "rgb(0, 0, 0)",
                                            "borderTopStyle": "none",
                                            "borderTopWidth": "0px",
                                            "textDecoration": "none",
                                            "borderLeftColor": "rgb(0, 0, 0)",
                                            "borderLeftStyle": "none",
                                            "borderLeftWidth": "0px",
                                            "borderRightColor": "rgb(0, 0, 0)",
                                            "borderRightStyle": "none",
                                            "borderRightWidth": "0px",
                                            "borderBottomColor": "rgb(0, 0, 0)",
                                            "borderBottomStyle": "none",
                                            "borderBottomWidth": "0px",
                                        },
                                    ],
                                },
                            },
                            {
                                "id": generateRandomId(),
                                "content": {
                                    "type": "phone",
                                    "components": [
                                        {
                                            "id": generateRandomId(),
                                            "text":
                                                localizedContent.phonePrefix,
                                            "type": "text",
                                            "color": "rgb(0, 0, 0)",
                                            "width": "0px",
                                            "height": "0px",
                                            "padding": "0px 0px 5px 0px",
                                            "fontSize": "14px",
                                            "fontStyle": "normal",
                                            "textAlign": "left",
                                            "fontFamily": "Verdana",
                                            "fontWeight": "normal",
                                            "lineHeight": "1",
                                            "borderRadius": "0px 0px 0px 0px",
                                            "letterSpacing": "0px",
                                            "borderTopColor": "rgb(0, 0, 0)",
                                            "borderTopStyle": "none",
                                            "borderTopWidth": "0px",
                                            "textDecoration": "none",
                                            "borderLeftColor": "rgb(0, 0, 0)",
                                            "borderLeftStyle": "none",
                                            "borderLeftWidth": "0px",
                                            "borderRightColor": "rgb(0, 0, 0)",
                                            "borderRightStyle": "none",
                                            "borderRightWidth": "0px",
                                            "borderBottomColor": "rgb(0, 0, 0)",
                                            "borderBottomStyle": "none",
                                            "borderBottomWidth": "0px",
                                        },
                                        {
                                            "id": generateRandomId(),
                                            "text": localizedContent.phoneValue,
                                            "type": "phoneLink",
                                            "color": "rgb(0, 0, 0)",
                                            "fontSize": "14px",
                                            "fontStyle": "normal",
                                            "textAlign": "left",
                                            "fontFamily": "Verdana",
                                            "fontWeight": "normal",
                                            "lineHeight": "1",
                                            "letterSpacing": "0px",
                                            "textDecoration": "none",
                                        },
                                    ],
                                },
                            },
                            {
                                "id": generateRandomId(),
                                "content": {
                                    "type": "email",
                                    "components": [
                                        {
                                            "id": generateRandomId(),
                                            "text":
                                                localizedContent.emailPrefix,
                                            "type": "text",
                                            "color": "rgb(0, 0, 0)",
                                            "width": "0px",
                                            "height": "0px",
                                            "padding": "0px 0px 10px 0px",
                                            "fontSize": "14px",
                                            "fontStyle": "normal",
                                            "textAlign": "left",
                                            "fontFamily": "Verdana",
                                            "fontWeight": "normal",
                                            "lineHeight": "1",
                                            "borderRadius": "0px 0px 0px 0px",
                                            "letterSpacing": "0px",
                                            "borderTopColor": "rgb(0, 0, 0)",
                                            "borderTopStyle": "none",
                                            "borderTopWidth": "0px",
                                            "textDecoration": "none",
                                            "borderLeftColor": "rgb(0, 0, 0)",
                                            "borderLeftStyle": "none",
                                            "borderLeftWidth": "0px",
                                            "borderRightColor": "rgb(0, 0, 0)",
                                            "borderRightStyle": "none",
                                            "borderRightWidth": "0px",
                                            "borderBottomColor": "rgb(0, 0, 0)",
                                            "borderBottomStyle": "none",
                                            "borderBottomWidth": "0px",
                                        },
                                        {
                                            "id": generateRandomId(),
                                            "text": localizedContent.emailValue,
                                            "type": "emailLink",
                                            "color": "rgb(0, 0, 0)",
                                            "fontSize": "14px",
                                            "fontStyle": "normal",
                                            "textAlign": "left",
                                            "fontFamily": "Verdana",
                                            "fontWeight": "normal",
                                            "lineHeight": "1",
                                            "letterSpacing": "0px",
                                            "textDecoration": "none",
                                        },
                                    ],
                                },
                            },
                            {
                                "id": generateRandomId(),
                                "content": {
                                    "type": "text",
                                    "components": [
                                        {
                                            "id": generateRandomId(),
                                            "text":
                                                localizedContent.addressValue,
                                            "color": "rgb(105, 105, 105)",
                                            "width": "0px",
                                            "height": "0px",
                                            "padding": "0px 0px 10px 0px",
                                            "fontSize": "14px",
                                            "fontStyle": "normal",
                                            "textAlign": "left",
                                            "fontFamily": "Verdana",
                                            "fontWeight": "normal",
                                            "lineHeight": "1",
                                            "borderRadius": "0px 0px 0px 0px",
                                            "letterSpacing": "0px",
                                            "borderTopColor": "rgb(0, 0, 0)",
                                            "borderTopStyle": "none",
                                            "borderTopWidth": "0px",
                                            "textDecoration": "none",
                                            "borderLeftColor": "rgb(0, 0, 0)",
                                            "borderLeftStyle": "none",
                                            "borderLeftWidth": "0px",
                                            "borderRightColor": "rgb(0, 0, 0)",
                                            "borderRightStyle": "none",
                                            "borderRightWidth": "0px",
                                            "borderBottomColor": "rgb(0, 0, 0)",
                                            "borderBottomStyle": "none",
                                            "borderBottomWidth": "0px",
                                        },
                                    ],
                                },
                            },
                            {
                                "id": generateRandomId(),
                                "content": {
                                    "type": "website",
                                    "components": [
                                        {
                                            "id": generateRandomId(),
                                            "text":
                                                localizedContent.websitePrefix,
                                            "type": "text",
                                            "color": "rgb(0, 0, 0)",
                                            "width": "0px",
                                            "height": "0px",
                                            "padding": "0px 0px 0px 0px",
                                            "fontSize": "14px",
                                            "fontStyle": "normal",
                                            "textAlign": "left",
                                            "fontFamily": "Verdana",
                                            "fontWeight": "normal",
                                            "lineHeight": "1",
                                            "borderRadius": "0px 0px 0px 0px",
                                            "letterSpacing": "0px",
                                            "borderTopColor": "rgb(0, 0, 0)",
                                            "borderTopStyle": "none",
                                            "borderTopWidth": "0px",
                                            "textDecoration": "none",
                                            "borderLeftColor": "rgb(0, 0, 0)",
                                            "borderLeftStyle": "none",
                                            "borderLeftWidth": "0px",
                                            "borderRightColor": "rgb(0, 0, 0)",
                                            "borderRightStyle": "none",
                                            "borderRightWidth": "0px",
                                            "borderBottomColor": "rgb(0, 0, 0)",
                                            "borderBottomStyle": "none",
                                            "borderBottomWidth": "0px",
                                        },
                                        {
                                            "id": generateRandomId(),
                                            "link":
                                                localizedContent.websiteLink,
                                            "text":
                                                localizedContent.websiteText,
                                            "type": "websiteLink",
                                            "color": "rgb(0, 0, 0)",
                                            "fontSize": "14px",
                                            "fontStyle": "normal",
                                            "textAlign": "left",
                                            "fontFamily": "Verdana",
                                            "fontWeight": "bold",
                                            "lineHeight": "1",
                                            "letterSpacing": "0px",
                                            "textDecoration": "none",
                                        },
                                    ],
                                },
                            },
                        ],
                        "style": {
                            "width": "auto",
                            "height": "auto",
                            "padding": "10px 10px 10px 0px",
                            "borderRadius": "0px 10px 10px 0px",
                            "verticalAlign": "top",
                            "borderTopColor": "rgb(61, 61, 61)",
                            "borderTopStyle": "solid",
                            "borderTopWidth": "2px",
                            "borderLeftColor": "rgb(0, 0, 0)",
                            "borderLeftStyle": "none",
                            "borderLeftWidth": "0px",
                            "borderRightColor": "rgb(61, 61, 61)",
                            "borderRightStyle": "solid",
                            "borderRightWidth": "2px",
                            "borderBottomColor": "rgb(61, 61, 61)",
                            "borderBottomStyle": "solid",
                            "borderBottomWidth": "2px",
                        },
                    },
                ],
            },
        ],
    };
};
